import test from 'node:test';
import assert from 'node:assert/strict';
import {setupModules} from './helpers.mjs';
const api=setupModules().load('navigationHistory');
function setup(){
  const listeners={},stack=[],pending=[],routes=[];let position=0,blocked=false;
  const host={history:{replaceState(state){stack[position]=state;},pushState(state){stack.splice(position+1);stack.push(state);position++;},go(delta){const next=position+delta;if(next>=0&&next<stack.length){position=next;pending.push(stack[position]);}}},addEventListener(name,fn){listeners[name]=fn;},removeEventListener(name,fn){if(listeners[name]===fn)delete listeners[name];}};
  const controller=api.createNavigationHistory(host,{page:'home'},target=>routes.push(target),()=>blocked);
  const fire=(name,props={})=>{let prevented=false;listeners[name]?.({type:name,preventDefault(){prevented=true;},...props});return prevented;};
  const flush=()=>{while(pending.length)fire('popstate',{state:pending.shift()});};
  return {controller,host,stack,routes,fire,flush,listeners,setBlocked:value=>blocked=value,position:()=>position};
}
test('side buttons traverse once and forward branch is replaced after a new navigation',()=>{const e=setup();e.controller.navigate({page:'tasks'});e.controller.navigate({page:'notes'});assert.equal(e.fire('mousedown',{button:3}),true);assert.equal(e.fire('mouseup',{button:3}),true);e.fire('auxclick',{button:3});e.flush();assert.equal(e.routes.at(-1).page,'tasks');e.fire('mouseup',{button:4});e.flush();assert.equal(e.routes.at(-1).page,'notes');e.fire('mouseup',{button:3});e.flush();e.controller.navigate({page:'projects'});e.fire('mouseup',{button:4});e.flush();assert.equal(e.routes.at(-1).page,'projects');assert.deepEqual(e.stack.map(s=>s.index),[0,1,2]);});
test('returning to a capture or speed test page strips one-shot intents',()=>{const e=setup();e.controller.navigate({page:'notes',intent:'new-note'});e.controller.navigate({page:'speed',intent:'start-speed'});e.controller.navigate({page:'archive',id:'saved'});e.fire('mouseup',{button:3});e.flush();assert.equal(e.routes.at(-1).intent,undefined);assert.equal(e.routes.at(-1).page,'speed');e.fire('mouseup',{button:3});e.flush();assert.equal(e.routes.at(-1).intent,undefined);assert.equal(e.routes.at(-1).page,'notes');});
test('blocked drafts/modal prevent mouse history and native popstate is restored without unmounting',()=>{const e=setup();e.controller.navigate({page:'tasks'});e.setBlocked(true);const count=e.routes.length;e.fire('mouseup',{button:3});assert.equal(e.position(),1);e.host.history.go(-1);e.flush();assert.equal(e.position(),1);assert.equal(e.routes.length,count);e.setBlocked(false);e.fire('mouseup',{button:3});e.flush();assert.equal(e.routes.at(-1).page,'home');});
test('keyboard browser/Alt arrows share history; middle/right clicks and Ctrl+K are untouched; cleanup removes listeners',()=>{const e=setup();e.controller.navigate({page:'tasks'});assert.equal(e.fire('keydown',{key:'k',ctrlKey:true}),false);assert.equal(e.fire('mouseup',{button:1}),false);assert.equal(e.fire('mouseup',{button:2}),false);assert.equal(e.fire('keydown',{key:'BrowserBack'}),true);e.flush();assert.equal(e.routes.at(-1).page,'home');e.fire('keydown',{key:'ArrowRight',altKey:true});e.flush();assert.equal(e.routes.at(-1).page,'tasks');e.controller.dispose();assert.equal(Object.keys(e.listeners).length,0);});
test('new direct navigation during asynchronous history travel is queued rather than lost',()=>{const e=setup();e.controller.navigate({page:'tasks'});e.controller.navigate({page:'notes'});e.fire('mouseup',{button:3});e.controller.navigate({page:'ai'});e.flush();assert.equal(e.routes.at(-1).page,'ai');assert.equal(e.position(),2);});
test('history guard ignores hidden settings, preserves blurred drafts, and blocks a focused editor or busy operation',()=>{
 const element=(hidden=false,value='draft')=>({value,closest:()=>hidden?{}:null,getClientRects:()=>[{}]});let modals=[],drafts=[],focused=false;
 const doc={activeElement:{closest:()=>focused?{}:null},querySelectorAll:selector=>selector.includes('dialog')?modals:drafts};
 assert.equal(api.navigationIsBlocked(doc,false),false);modals=[element(true)];assert.equal(api.navigationIsBlocked(doc,false),false);modals=[element()];assert.equal(api.navigationIsBlocked(doc,false),true);modals=[];drafts=[element()];assert.equal(api.navigationIsBlocked(doc,false),true);drafts=[element(false,'')];assert.equal(api.navigationIsBlocked(doc,false),false);focused=true;assert.equal(api.navigationIsBlocked(doc,false),true);focused=false;assert.equal(api.navigationIsBlocked(doc,true),true);
});
