import test from 'node:test';
import assert from 'node:assert/strict';
import {setupModules} from './helpers.mjs';
const plain=v=>JSON.parse(JSON.stringify(v));
const project={id:'project-1',name:'Özgehan',description:'Otomotiv',folderPath:'C:/private/site',nextStep:'Menüyü kontrol et'};
const task={id:'task-1',text:'Mobil menü',completed:false,projectId:project.id,checklist:[{id:'step-1',text:'Telefon testi',completed:false}],dueDate:'2026-10-08',dueTime:'14:00',reminder:true,reminderLeadMinutes:60};
const note={id:'note-1',title:'Menü notu',content:'UART örneği',updatedAt:1,projectId:project.id};
const fixture=()=>setupModules([['ack-deck.projects.v1',JSON.stringify([project])],['ack-deck.tasks.v1',JSON.stringify([task])],['ack-deck.notes.v1',JSON.stringify([note])]]);
test('template capacity rejects a new template rather than silently deleting an existing user template',()=>{
 const env=fixture(),api=env.load('templateStore'),templates=Array.from({length:100},(_,i)=>({...api.RELEASE_TEMPLATE,id:'template-'+i}));env.values.set(api.TEMPLATE_KEY,JSON.stringify(templates));assert.equal(api.saveTemplate({...api.RELEASE_TEMPLATE,id:'new-template'}),false);assert.equal(JSON.parse(env.values.get(api.TEMPLATE_KEY)).length,100);assert.equal(JSON.parse(env.values.get(api.TEMPLATE_KEY))[99].id,'template-99');assert.equal(api.saveTemplate({...templates[50],name:'Güncellendi'}),true);assert.equal(api.loadTemplates().entries[0].name,'Güncellendi');
});
test('AI note extraction is bound to a stable ID and linked note creation is confirmed through the existing store',async()=>{
 const env=fixture(),reads=env.load('ackIntegration'),actions=env.load('ackActions');
 const context=await reads.collectAckContext(`Not ID: ${note.id} — bu nottan 3 görev çıkar.`);assert.ok(context.context.some(c=>c.source==='notes'&&JSON.parse(c.data)[0].id===note.id));
 const proposal=actions.prepareAckProposal({type:'create_note',title:'Yeni not',content:'Özet',projectId:project.id});await assert.rejects(actions.executeAckAction(proposal.action,false));await actions.executeAckAction(proposal.action,true,undefined,undefined,proposal.expected);assert.equal(env.load('notesStore').loadNotes().notes[0].projectId,project.id);
 const completed={...task,completed:true};env.values.set('ack-deck.tasks.v1',JSON.stringify([completed]));await actions.executeAckAction({type:'complete_task',taskId:task.id},true);assert.equal(env.load('taskStore').loadTasks().entries[0].completed,true);
});
test('large project context stays valid JSON and bounded while retaining aggregate checklist progress',()=>{
 const env=fixture(),api=env.load('productIntelligence'),data=api.intelligenceData();
 data.tasks=Array.from({length:40},(_,i)=>({...task,id:'task-'+i,checklist:Array.from({length:100},(_,j)=>({id:'step-'+j,text:'x'.repeat(200),completed:j%2===0}))}));
 const context=api.buildIntelligenceContext('Özgehan projesinde ne var?',data);
 assert.ok(context.text.length<=12000);const parsed=JSON.parse(context.text);assert.equal(parsed.data.checklist.total,4000);assert.equal(parsed.data.checklist.done,2000);assert.ok(context.records.length<=20);
});
test('every recurring occurrence has its own reminder, including reminders that cross a week or DST boundary',()=>{
 const env=fixture(),api=env.load('../shared/weeklyPlan'),rec=env.load('../shared/recurrence');
 const rule={frequency:'daily',interval:1,weekdays:[],dayOfMonth:7,start:'2026-10-05',time:'20:00',timezone:'Europe/Istanbul',endDate:null,count:8};
 const events=api.weeklyPlan([{...task,recurrence:rule,dueAt:rec.zonedAt(rule.start,rule.time,rule.timezone),occurrenceAt:rec.zonedAt(rule.start,rule.time,rule.timezone),reminderLeadMinutes:1440}],[],new Date('2026-10-07T12:00:00'));
 assert.equal(events.filter(e=>!e.reminder).length,7);assert.equal(events.filter(e=>e.reminder).length,7);assert.ok(events.some(e=>e.reminder&&e.date==='2026-10-11'));
 assert.deepEqual(plain(api.weekDates(new Date('2027-01-01T12:00:00'))),['2026-12-28','2026-12-29','2026-12-30','2026-12-31','2027-01-01','2027-01-02','2027-01-03']);
 const dst={...rule,start:'2026-10-26',timezone:'America/New_York',count:7,time:'20:00'};
 const week=api.weeklyPlan([{...task,recurrence:dst,reminderLeadMinutes:60}],[],new Date('2026-10-28T12:00:00'));
 assert.equal(week.filter(e=>!e.reminder).length,7);assert.equal(week.filter(e=>e.reminder).length,7);assert.ok(week.filter(e=>e.reminder).every(e=>e.time==='19:00'));
});
test('AI context references navigate only to actual bounded IDs, never arbitrary paths or unknown pages',()=>{
 const env=fixture(),api=env.load('ackIntegration');
 assert.deepEqual(plain(api.contextReferences([{source:'notes',data:JSON.stringify([{id:note.id,title:note.title},{id:'C:/private',title:'Bad'}])},{source:'shortcuts',data:JSON.stringify([{id:'shortcut-1',name:'Kısayol'}])},{source:'recent',data:JSON.stringify([{id:'unknown',source:'shell',name:'Bad'}])}])),[{source:'notes',id:note.id,label:note.title},{source:'files',id:'shortcut-1',label:'Kısayol'}]);
});
test('stable project links, checklist order and next step survive the existing stores; old data stays valid',()=>{
 const env=fixture(),tasks=env.load('taskStore'),projects=env.load('projectStore');assert.equal(tasks.isTask({id:'old',text:'Old',completed:false}),true);
 const changed={...task,checklist:[{id:'step-2',text:'Build',completed:false},{id:'step-1',text:'Telefon testi',completed:true}]};assert.equal(tasks.saveTasks([changed],tasks.loadTasks()),true);assert.deepEqual(plain(tasks.loadTasks().entries[0].checklist),changed.checklist);
 assert.equal(projects.saveProjects([{...project,nextStep:'Yeni adım'}]),true);assert.equal(projects.loadProjects()[0].folderPath,project.folderPath);
 const hub=env.load('productIntelligence').projectHub(project.id);assert.equal(hub.tasks.length,1);assert.equal(hub.notes[0].id,note.id);assert.deepEqual(plain(hub.checklist),{done:1,total:2});assert.equal(hub.project.nextStep,'Yeni adım');
});
test('invalid checklist IDs, duplicate steps and malformed links are rejected without deleting old records',()=>{const env=fixture(),store=env.load('taskStore');for(const patch of [{projectId:'C:/raw/path'},{checklist:[{id:'x',text:'A',completed:false},{id:'x',text:'B',completed:false}]},{checklist:[{id:'../x',text:'A',completed:false}]},{reminderLeadMinutes:-1}])assert.equal(store.saveTasks([{...task,...patch}],store.loadTasks()),false);assert.equal(store.loadTasks().entries[0].text,task.text);});
test('activity is bounded, local, coalesces autosaves and respects retention and unreadable storage',()=>{const env=fixture(),api=env.load('activityStore'),now=Date.now();for(let i=0;i<1005;i++)api.recordActivity({source:'tasks',recordId:'t',kind:'completed',label:'Task'},now+i);assert.equal(api.loadActivity().entries.length,1000);api.recordActivity({source:'notes',recordId:'n',kind:'updated',label:'Note'},now+1006);api.recordActivity({source:'notes',recordId:'n',kind:'updated',label:'Note updated'},now+1007);assert.equal(api.loadActivity().entries.filter(a=>a.source==='notes').length,1);api.recordActivity({source:'tasks',recordId:'t',kind:'created',label:'Later'},now+91*86400000);assert.equal(api.loadActivity().entries.length,1);env.values.set(api.ACTIVITY_KEY,'broken');assert.equal(api.recordActivity({source:'tasks',recordId:'t',kind:'created',label:'No write'}),false);assert.equal(env.values.get(api.ACTIVITY_KEY),'broken');});
test('recurring completion advances the same series and preserves metadata/checklist',()=>{const env=fixture(),r=env.load('../shared/recurrence'),rule={frequency:'daily',interval:1,weekdays:[],dayOfMonth:8,start:'2026-10-08',time:'14:00',timezone:'Europe/Istanbul',endDate:null,count:null},at=r.zonedAt(rule.start,rule.time,rule.timezone),result=r.completeOccurrence({...task,recurrence:rule,occurrenceAt:at},at);assert.equal(result.id,task.id);assert.equal(result.projectId,project.id);assert.deepEqual(plain(result.checklist),task.checklist);assert.equal(result.dueDate,'2026-10-09');});
test('templates create a fresh task/checklist with project/workspace IDs and never execute release actions',()=>{const env=fixture(),api=env.load('templateStore'),one=api.templateTask(api.RELEASE_TEMPLATE,project.id,'w'),two=api.templateTask(api.RELEASE_TEMPLATE,project.id,'w');assert.notEqual(one.id,two.id);assert.notEqual(one.checklist[0].id,two.checklist[0].id);assert.equal(one.projectId,project.id);assert.equal(one.workspaceId,'w');assert.equal(env.calls.length,0);assert.equal(api.saveTemplate({...api.RELEASE_TEMPLATE,id:'custom'}),true);assert.equal(api.loadTemplates().entries.length,1);});
test('Inbox conversions reuse existing stores, preserve attachments, prevent duplicate conversion and link IDs',()=>{const env=fixture(),api=env.load('inboxProcessing'),file={id:'voice-1',name:'ses.ogg',mime:'audio/ogg',size:20},draft={sourceId:'voice-1',title:'Toplantı',content:'Özet',projectId:project.id,attachment:file};assert.equal(api.inboxToTask(draft,'new-task'),'new-task');assert.equal(api.inboxToTask(draft,'second-task'),'new-task');api.inboxToNote(draft,'new-note');assert.equal(api.inboxToNote(draft,'other-note'),'new-note');api.inboxToNote({...draft,sourceId:'text-2',attachment:undefined},'unused',note.id);assert.match(env.load('notesStore').loadNotes().notes.find(n=>n.id===note.id).content,/UART örneği\n\nÖzet/);api.linkInboxProject(draft.sourceId,project.id);assert.deepEqual(plain(env.load('projectStore').loadProjects()[0].inboxIds),['voice-1']);api.inboxToArchive(draft,'archive-1');assert.deepEqual(plain(env.load('archiveStore').loadArchive().entries[0].attachments),[file]);});
test('single-line capture previews Turkish dates, recurrence, reminders, project tasks and notes deterministically',()=>{const env=fixture(),api=env.load('../shared/smartCapture'),now=new Date('2026-10-07T12:00:00');let draft=api.parseSmartCapture('yarın 14:00 kargoyu ara 1 saat önce hatırlat',[project],now,'Europe/Istanbul');assert.equal(draft.text,'kargoyu ara');assert.equal(draft.dueDate,'2026-10-08');assert.equal(draft.reminderLeadMinutes,60);draft=api.parseSmartCapture('her pazartesi 20:00 elektronik çalış',[project],now,'Europe/Istanbul');assert.deepEqual(plain(draft.recurrence.weekdays),[1]);draft=api.parseSmartCapture('Özgehan projesine mobil menüyü düzelt görevi ekle',[project],now);assert.equal(draft.projectId,project.id);assert.equal(draft.text,'mobil menüyü düzelt');assert.equal(api.parseSmartCapture('şunu not al: UART TX geri dönüşünü kontrol et').kind,'note');assert.equal(api.parseSmartCapture('yarın 25:90 yanlış saat'),null);assert.equal(env.values.size,3);assert.equal(env.calls.length,0);});
test('week boundaries, recurring occurrences, summaries and reminder lead use existing dates',()=>{const env=fixture(),api=env.load('../shared/weeklyPlan'),now=new Date('2026-10-07T12:00:00'),rec=env.load('../shared/recurrence');assert.deepEqual(plain(api.weekDates(now)),['2026-10-05','2026-10-06','2026-10-07','2026-10-08','2026-10-09','2026-10-10','2026-10-11']);const rule={frequency:'daily',interval:1,weekdays:[],dayOfMonth:7,start:'2026-10-07',time:'20:00',timezone:'Europe/Istanbul',endDate:null,count:3};const events=api.weeklyPlan([{...task,dueAt:rec.zonedAt('2026-10-08','14:00','Europe/Istanbul'),timezone:'Europe/Istanbul'},{...task,id:'daily',reminder:false,recurrence:rule}],[],now);assert.equal(events.filter(e=>e.id==='daily').length,3);assert.equal(events.find(e=>e.id===task.id&&e.reminder).time,'13:00');assert.equal(api.todaySummary([task,{...task,id:'old',dueDate:'2026-10-01'}],[],2,now).overdue,1);});
test('where-left-off and weekly summary use real bounded records, omit paths and expose stable navigation references',()=>{const env=fixture(),activity=env.load('activityStore'),now=Date.now();activity.recordActivity({source:'tasks',recordId:task.id,projectId:project.id,kind:'completed',label:'Mobil not ekranı'},now);const api=env.load('productIntelligence'),context=api.buildIntelligenceContext('Özgehan projesinde nerede kalmıştım?');assert.ok(!context.text.includes(project.folderPath));assert.equal(context.records[0].id,project.id);const answer=api.localIntelligenceAnswer('Özgehan projesinde nerede kalmıştım?');assert.match(answer.answer,/Menüyü kontrol et/);assert.match(answer.answer,/Mobil not ekranı/);assert.match(api.localIntelligenceAnswer('Bu hafta ne yaptım?').answer,/1 görev tamamlanması/);});
test('AI batches and smart capture require single-use approval and reject stale records, nested/native actions',async()=>{const env=fixture(),api=env.load('ackActions'),confirmation=env.load('ackConfirmation');const proposal=api.prepareAckProposal({type:'batch',actions:[{type:'complete_task',taskId:task.id},{type:'update_project',projectId:project.id,nextStep:'Installer testi'}]});const ticket=confirmation.createConfirmation(proposal);await assert.rejects(api.executeAckAction(proposal.action,false));const approved=confirmation.claimConfirmation(ticket);await api.executeAckAction(approved.action,true,undefined,undefined,approved.expected);assert.equal(env.load('taskStore').loadTasks().entries[0].completed,true);assert.equal(env.load('projectStore').loadProjects()[0].nextStep,'Installer testi');assert.throws(()=>confirmation.claimConfirmation(ticket));assert.throws(()=>api.prepareAckProposal({type:'batch',actions:[{type:'open_project',projectId:project.id,mode:'folder'}]}));assert.throws(()=>api.prepareAckProposal({type:'batch',actions:[{type:'batch',actions:[]}]}));const stale=api.prepareAckProposal({type:'update_project',projectId:project.id,nextStep:'Stale'});const store=env.load('projectStore');store.saveProjects([{...store.loadProjects()[0],nextStep:'Changed'}]);await assert.rejects(api.executeAckAction(stale.action,true,undefined,undefined,stale.expected));});
test('backup/restore includes project/checklist/activity/templates and excludes auth/cache/pending actions',async()=>{const env=fixture(),templates=env.load('templateStore');templates.saveTemplate(templates.RELEASE_TEMPLATE);env.load('activityStore').recordActivity({source:'tasks',recordId:task.id,kind:'created',label:task.text});env.values.set('ack-deck.phone-sync.v1','private device state');env.values.set('ack-deck.pending-action','sensitive');const api=env.load('backupStore'),desktop={closeToTray:true,startInTray:false,autoStart:false},backup=api.createBackup(desktop,'1.1.3');assert.equal(backup.data.tasks[0].checklist[0].id,'step-1');assert.equal(backup.data.projects[0].nextStep,project.nextStep);assert.equal(backup.data.activity.length,1);assert.equal(backup.data.templates.length,1);assert.ok(!JSON.stringify(backup).includes('private device state'));assert.ok(!JSON.stringify(backup).includes('sensitive'));await api.restoreBackup(backup,true,desktop,env.storage,async()=>{});assert.equal(env.load('projectStore').loadProjects()[0].folderPath,project.folderPath);});
