import { NoteEditor } from "./NoteEditor";
import { NotesList } from "./NotesList";
import { RecurrenceFields } from "../../shared/RecurrenceFields";
import { SubscriptionForm, newSubscription } from "../../shared/SubscriptionForm";
import { money, cycleLabel, paymentLabel, monthlyTotals, type Subscription } from "../../shared/subscriptions";
import { completeOccurrence, nextOccurrence, recurrenceLabel, type Recurrence } from "../../shared/recurrence";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { createRoot } from "react-dom/client";
import { MAX_ATTACHMENT, type CloudRecord, type PhoneTask, type PhoneNote, type Mutation } from "../../shared/phone";
import { api, emptyState, enqueue, json, readState, saveState, synchronize, type MobileState } from "./store";
import { enablePush } from "./push";
import "./style.css";
import "./notes.css";
import { SendCard } from "./SendCard";
import { MobileNav } from "./MobileNav";
import { Icon } from "./Icon";
type Inbox = {id:string;kind:string;title:string;content:string;mime:string|null;expiresAt:number|null;handled:number};
type Workspace = {id:string;name:string;icon:string;description:string};
const dateKey = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
function App() {
  const [state,setState] = useState<MobileState>(emptyState), [ready,setReady] = useState(false), [page,setPage] = useState(new URLSearchParams(location.hash.slice(1)).get("page")==="subscriptions"?"subscriptions":"today"), [busy,setBusy] = useState(false), [error,setError] = useState(""), [notice,setNotice] = useState("");
  const [form,setForm] = useState<"task"|"note"|"text"|"link"|"ai_prompt"|null>(null), [editing,setEditing] = useState<CloudRecord|null>(null), [title,setTitle] = useState(""), [content,setContent] = useState(""), [date,setDate] = useState(""), [time,setTime] = useState(""), [important,setImportant] = useState(false), [reminder,setReminder] = useState(false);
  const [recurrence,setRecurrence]=useState<Recurrence|null>(null),[subscriptionDraft,setSubscriptionDraft]=useState<Subscription|null>(null),[quickAdd,setQuickAdd]=useState(false);
  const [undo,setUndo]=useState<{row:CloudRecord;expires:number}|null>(null);
  const [notificationTask,setNotificationTask]=useState(()=>new URLSearchParams(location.hash.slice(1)).get("task"));
  const formRequestId=useRef(crypto.randomUUID());
  function changePage(next: string) { setPage(next); setQuickAdd(false); window.scrollTo({ top: 0 }); }
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(""), 4000); return () => clearTimeout(timer); }, [notice]);
  const [code,setCode] = useState(() => new URLSearchParams(location.hash.slice(1)).get("pair") ?? ""), [name,setName] = useState("iPhone"), [online,setOnline] = useState(false), [push,setPush] = useState(false), [inbox,setInbox] = useState<Inbox[]>([]), [workspaces,setWorkspaces] = useState<Workspace[]>([]), [recording,setRecording] = useState(false), [audio,setAudio] = useState<Blob|null>(null);
  const editorRef=useRef<HTMLElement|null>(null),subscriptionEditorRef=useRef<HTMLElement|null>(null);
  const closeFormRef=useRef(closeForm);closeFormRef.current=closeForm;
  useEffect(()=>{
    const dialog=editorRef.current??subscriptionEditorRef.current;if(!dialog)return;
    const previous=document.activeElement as HTMLElement|null;
    const controls=()=>Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),summary')).filter(el=>el.getClientRects().length);
    if (!dialog.contains(document.activeElement)) controls()[0]?.focus();
    const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){closeFormRef.current();setSubscriptionDraft(null);}if(event.key!=="Tab")return;const all=controls(),first=all[0],last=all[all.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}};
    const resize=()=>{dialog.style.height=(window.visualViewport?.height??window.innerHeight)+"px";};resize();window.visualViewport?.addEventListener("resize",resize);window.addEventListener("keydown",key);
    return()=>{window.removeEventListener("keydown",key);window.visualViewport?.removeEventListener("resize",resize);previous?.focus();};
  },[!!form,!!subscriptionDraft]);
  useEffect(()=>{if(!undo)return;const timer=setTimeout(()=>setUndo(null),Math.max(0,undo.expires-Date.now()));return()=>clearTimeout(timer);},[undo]);
  const ref = useRef(state), locked = useRef(false), recorder = useRef<MediaRecorder|null>(null), stream = useRef<MediaStream|null>(null), recordingTimer = useRef<ReturnType<typeof setTimeout>|null>(null);
  const pageRef=useRef(page);pageRef.current=page;
  ref.current = state;
  async function commit(value: MobileState) { await saveState(value); ref.current = value; setState(value); }
  async function refresh(value = ref.current) {
    if (!value.token || locked.current) return;
    locked.current = true; setBusy(true); setError("");
    try {
      const next = await synchronize(value); ref.current=next; setState(next);
      const [status,list,spaces] = await Promise.all([api<{online:boolean;notifications:boolean}>(next,"status"),api<{items:Inbox[]}>(next,"inbox"),api<{workspaces:Workspace[]}>(next,"workspaces")]);
      setOnline(status.online); setPush(status.notifications); setInbox(list.items); setWorkspaces(spaces.workspaces); setNotice(next.conflicts.length ? "Eşitleme çakışması var; iki sürüm de korundu." : "Eşitlendi.");
    } catch (e) { setError(navigator.onLine ? e instanceof Error ? e.message : "Eşitleme tamamlanamadı." : "Çevrimdışı — bağlantı gelince eşitlenecek."); try { const saved=await readState(); ref.current=saved;setState(saved); } catch {} }
    finally { locked.current=false;setBusy(false); }
  }
  useEffect(() => {
    let active=true;
    void readState().then(value => { if (active) { ref.current=value;setState(value);setName(value.name);setReady(true);void refresh(value); } }).catch(() => setError("Telefon kayıtları okunamadı. Mevcut veriler korundu."));
    const reconnect=()=>{void refresh();};window.addEventListener("online",reconnect);
    return()=>{active=false;window.removeEventListener("online",reconnect);if(recordingTimer.current)clearTimeout(recordingTimer.current);if(recorder.current&&recorder.current.state!=="inactive")recorder.current.stop();stream.current?.getTracks().forEach(track=>track.stop());};
  },[]);
  useEffect(()=>{const stop=()=>{if(document.hidden&&recorder.current&&recorder.current.state!=="inactive"){recorder.current.stop();stream.current?.getTracks().forEach(track=>track.stop());}};document.addEventListener("visibilitychange",stop);return()=>document.removeEventListener("visibilitychange",stop);},[]);
  useEffect(()=>{if(page!=="inbox"&&recorder.current&&recorder.current.state!=="inactive"){recorder.current.stop();stream.current?.getTracks().forEach(track=>track.stop());}},[page]);
  async function pair(event: FormEvent) {
    event.preventDefault(); if(!ready||locked.current)return;locked.current=true;setBusy(true);setError("");
    try {const result=await api<{token:string}>(state,"pair/exchange",json({code:code.trim(),name:name.trim()}));const next={...state,token:result.token,name:name.trim()};await commit(next);history.replaceState(null,"",location.pathname);setCode("");setNotice("Telefon eşleştirildi.");locked.current=false;void refresh(next);}
    catch(e){setError(e instanceof Error?e.message:"Eşleştirme tamamlanamadı.");}finally{locked.current=false;setBusy(false);}
  }
  function openForm(kind: NonNullable<typeof form>, row:CloudRecord|null=null) {
    const task=row?.kind==="tasks"?row.data as PhoneTask:null;
    setError("");formRequestId.current=crypto.randomUUID();setForm(kind);setEditing(row);setTitle(row?.kind==="notes"?(row.data as PhoneNote).title:task?.text??"");setContent(row?.kind==="notes"?(row.data as PhoneNote).content:"");setDate(task?.dueDate??"");setTime(task?.dueTime??"");setImportant(task?.priority==="important");setReminder(task?.reminder??false);setRecurrence(task?.recurrence??null);
  }
  useEffect(()=>{const taskId=notificationTask;if(!taskId||!ready)return;const row=state.records.find(item=>item.kind==="tasks"&&item.id===taskId&&!item.deleted);if(row){setPage("today");openForm("task",row);history.replaceState(null,"",location.pathname);setNotificationTask(null);}},[ready,state.records,notificationTask]);
  useEffect(()=>{const change=()=>{const hash=new URLSearchParams(location.hash.slice(1));setNotificationTask(hash.get("task"));if(hash.get("page")==="subscriptions")setPage("subscriptions");};window.addEventListener("hashchange",change);return()=>window.removeEventListener("hashchange",change);},[]);
  useEffect(()=>{if(!form)return;const escape=(event:KeyboardEvent)=>{if(event.key==="Escape" && form!=="note")setForm(null);};window.addEventListener("keydown",escape);return()=>window.removeEventListener("keydown",escape);},[form]);
  function closeForm() { if(busy)return;const previous=editing?.data as PhoneNote|undefined;if(form==="note"&&(title!==(previous?.title??"")||content!==(previous?.content??""))&&!confirm("Kaydedilmemiş değişikliklerden vazgeçilsin mi? Kaydet düğmesiyle kaydedebilirsin."))return;setForm(null); }
  async function saveMutation(mutation: Mutation) {
    if(locked.current)throw new Error("Eşitleme sürüyor. Biraz sonra deneyin.");
    locked.current=true;let next:MobileState;try{next=enqueue(ref.current,mutation);await commit(next);}finally{locked.current=false;}setNotice(navigator.onLine?"Kaydedildi; eşitleniyor…":"Çevrimdışı — bağlantı gelince eşitlenecek.");void refresh(next);
  }
  async function submit(event:FormEvent) {
    event.preventDefault();setError("");
    try {
      if(form==="task") {
        const previous=editing?.data as PhoneTask|undefined;
        const changed=JSON.stringify(recurrence)!==JSON.stringify(previous?.recurrence??null)||date!==previous?.dueDate||time!==previous?.dueTime;
        const rule=recurrence&&changed?{...recurrence,start:date,time}:recurrence;
        const first=rule&&changed?nextOccurrence(rule,Date.parse(date+"T00:00:00Z")-86400000):null;
        if(rule&&(!date||!time||changed&&!first))throw new Error("Tekrar için tarih, saat ve günleri kontrol edin.");
        const dueAt=first?.at??(!changed&&previous?.snoozedUntil?previous.snoozedUntil:rule?previous?.dueAt??null:date&&time?new Date(`${date}T${time}:00`).getTime():null);
        await saveMutation({mutationId:crypto.randomUUID(),kind:"tasks",id:editing?.id??crypto.randomUUID(),baseVersion:editing?.version??0,deleted:false,data:{text:title.trim(),completed:rule&&changed?false:editing?.data&&"completed" in editing.data?editing.data.completed:false,dueDate:first?.date??(date||null),dueTime:time||null,recurrence:rule,occurrenceAt:first?.at??previous?.occurrenceAt??dueAt,lastCompletedAt:previous?.lastCompletedAt??null,snoozedUntil:changed?null:previous?.snoozedUntil??null,priority:important?"important":"normal",reminder,dueAt,timezone:rule?.timezone??Intl.DateTimeFormat().resolvedOptions().timeZone}});
      } else if(form==="note") await saveMutation({mutationId:crypto.randomUUID(),kind:"notes",id:editing?.id??crypto.randomUUID(),baseVersion:editing?.version??0,deleted:false,data:{title:title.trim()||content.trim().slice(0,60),content:content.trim(),updatedAt:Date.now()}});
      else { if(!navigator.onLine)throw new Error("Bu gönderi için internet gerekir. Metniniz burada korunuyor.");await api(state,"inbox",json({id:formRequestId.current,kind:form,title:title.trim()||content.slice(0,60),content:content.trim()}));setNotice("Gönderildi.");void refresh(); }
      setForm(null);setEditing(null);
    }catch(e){setError(e instanceof Error?e.message:"Kaydedilemedi.");}
  }
  async function complete(row:CloudRecord){try{await saveMutation({mutationId:crypto.randomUUID(),kind:"tasks",id:row.id,baseVersion:row.version,deleted:false,data:completeOccurrence(row.data as PhoneTask)});}catch(e){setError(e instanceof Error?e.message:"Görev kaydedilemedi.");}}
  async function snooze(row:CloudRecord,minutes:number){const task=row.data as PhoneTask;const future=new Date();if(minutes===1440)future.setDate(future.getDate()+1);else future.setMinutes(future.getMinutes()+minutes);future.setSeconds(0,0);try{await saveMutation({mutationId:crypto.randomUUID(),kind:"tasks",id:row.id,baseVersion:row.version,deleted:false,data:{...task,snoozedUntil:future.getTime(),occurrenceAt:task.occurrenceAt??task.dueAt,dueDate:task.recurrence?task.dueDate:dateKey(future),dueTime:task.recurrence?task.dueTime:`${String(future.getHours()).padStart(2,"0")}:${String(future.getMinutes()).padStart(2,"0")}`,dueAt:future.getTime(),timezone:task.recurrence?.timezone??task.timezone,reminder:true,completed:false}});}catch{setError("Hatırlatma ertelenemedi.");}}
  async function upload(blob:Blob,name:string){if(!navigator.onLine){setError("Dosya göndermek için internet gerekir.");return;}if(blob.size>MAX_ATTACHMENT){setError("Dosya en fazla 10 MB olabilir.");return;}setBusy(true);try{await api(state,"attachments",{method:"POST",headers:{"Content-Type":blob.type||"application/octet-stream","X-File-Name":encodeURIComponent(name),"X-Request-Id":crypto.randomUUID()},body:blob});setNotice("Dosya gönderildi. Bulutta 30 gün saklanır.");setAudio(null);void refresh();}catch(e){setError(e instanceof Error?e.message:"Dosya gönderilemedi.");}finally{setBusy(false);}}
  async function startRecording(){setError("");if(!navigator.mediaDevices?.getUserMedia||!("MediaRecorder" in window)){setError("Ses kaydı bu cihazda desteklenmiyor. Mevcut bir ses dosyasını seçebilirsiniz.");return;}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});if(document.hidden||pageRef.current!=="inbox"){stream.current.getTracks().forEach(track=>track.stop());throw new Error("Kayıt iptal edildi.");}const mime=["audio/mp4","audio/webm","audio/ogg"].find(type=>MediaRecorder.isTypeSupported(type));const rec=new MediaRecorder(stream.current,mime?{mimeType:mime}:undefined);const chunks:BlobPart[]=[];let size=0;rec.ondataavailable=e=>{size+=e.data.size;if(size>MAX_ATTACHMENT){setError("Sesli not en fazla 10 MB olabilir.");rec.stop();return;}chunks.push(e.data);};rec.onstop=()=>{if(recordingTimer.current)clearTimeout(recordingTimer.current);stream.current?.getTracks().forEach(track=>track.stop());setRecording(false);if(size<=MAX_ATTACHMENT)setAudio(new Blob(chunks,{type:rec.mimeType.split(";")[0]}));};recorder.current=rec;rec.start(1000);setRecording(true);recordingTimer.current=setTimeout(()=>rec.state!=="inactive"&&rec.stop(),120000);}catch{setError("Mikrofon açılamadı. İzni cihaz ayarlarından kontrol edin.");}}
  const tasks=state.records.filter(row=>row.kind==="tasks"&&!row.deleted&&row.data),today=dateKey();
  const unfinished=tasks.filter(row=>!(row.data as PhoneTask).completed).sort((a,b)=>((a.data as PhoneTask).dueDate??"9999").localeCompare((b.data as PhoneTask).dueDate??"9999")||((a.data as PhoneTask).dueTime??"").localeCompare((b.data as PhoneTask).dueTime??""));
  const visible=[...unfinished.filter(row=>!!(row.data as PhoneTask).dueDate&&(row.data as PhoneTask).dueDate!<=today),...unfinished.filter(row=>(row.data as PhoneTask).dueDate!>today).slice(0,3),...unfinished.filter(row=>!(row.data as PhoneTask).dueDate).slice(0,3)];
  if(!state.token)return <main className="pairing-page"><header><img src="/icon-192.png" alt="ACK"/><h1>ACKDeck Mobile</h1></header><div className="pairing-intro"><span className="mobile-eyebrow">TELEFON VE BİLGİSAYAR</span><h2>Her şey yanında.</h2><p>Görevlerin, notların ve aboneliklerin tek yerde.</p></div><h3>Telefonunu eşleştir</h3><p>Safari paylaşım menüsünden Ana Ekrana Ekle'yi seçin. Uygulamayı Ana Ekranınızdan açıp bilgisayardaki Telefon bölümünün kodunu girin.</p><form onSubmit={pair}><label>Cihaz adı<input value={name} onChange={e=>setName(e.target.value)} required maxLength={80}/></label><label>Eşleştirme kodu<input autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} required/></label><button disabled={busy||!ready}>Eşleştir</button></form>{error&&<p role="alert" className="error">{error}</p>}</main>;
  return <main className={"mobile-app " + (page==="notes"?"notes-page":"")}><div className="mobile-content" inert={!!form || !!subscriptionDraft}><header className="mobile-header"><img src="/icon-192.png" alt="ACK"/><div><strong>ACKDeck</strong><span>{new Date().toLocaleDateString("tr-TR", { day: "numeric", month: "long", weekday: "short" })}</span></div><button type="button" className="refresh-button" aria-label="Kayıtları yenile" disabled={busy} onClick={()=>void refresh()}><Icon name="refresh" size={20}/></button></header><div className="mobile-sync-status"><span className={online ? "online" : ""}>PC {online?"çevrimiçi":"çevrimdışı"}</span><span>{busy ? "Eşitleniyor…" : state.queue.length ? `${state.queue.length} kayıt bekliyor` : "Güncel"}</span></div><div className="mobile-page-heading">{["work","subscriptions","settings"].includes(page)&&<button type="button" className="mobile-back" onClick={()=>changePage("more")}><span aria-hidden="true">‹</span> Diğer</button>}<h1>{{today:"Bugün",inbox:"Gönderilenler",work:"Çalışma Alanları",more:"Diğer",notes:"Notlar",subscriptions:"Abonelikler",settings:"Ayarlar"}[page] ?? "Bugün"}</h1><p>{{today:"Günün akışını bir bakışta gör.",inbox:"Telefondan bilgisayarına kolayca gönder.",work:"Bilgisayardaki çalışma alanlarını başlat.",more:"Kayıtların ve uygulama tercihlerin.",notes:"Aklındakileri yanında tut.",subscriptions:"Ödemelerini ve yenilemelerini takip et.",settings:"Cihazını ve bildirimlerini yönet."}[page]}</p></div>{error&&<p role="alert" className="error">{error}</p>}
    {page==="today"&&<><div className="today-overview"><strong>{unfinished.length}</strong><span>bekleyen görev</span><small>{tasks.filter(row=>(row.data as PhoneTask).completed).length} tamamlandı</small></div><button className="primary-action" onClick={()=>setQuickAdd(!quickAdd)}>+ Hızlı ekle</button>{quickAdd&&<div className="quick-add actions">{[["task","Görev"],["note","Not"],["link","Link"]].map(([key,label])=><button key={key} onClick={()=>{openForm(key as NonNullable<typeof form>);setQuickAdd(false);}}>{label}</button>)}<button onClick={()=>{setPage("inbox");setQuickAdd(false);}}>Dosya / Sesli not</button></div>}{!visible.length&&<p>Bugün için bekleyen göreviniz yok.</p>}{visible.map((row,index)=>{const task=row.data as PhoneTask;const group=!task.dueDate?"Tarihsiz":task.dueDate<today?"Geciken":task.dueDate===today?"Bugün":"Yaklaşan";const prev=index?visible[index-1].data as PhoneTask:null;const previousGroup=prev?(!prev.dueDate?"Tarihsiz":prev.dueDate<today?"Geciken":prev.dueDate===today?"Bugün":"Yaklaşan"):null;return <section key={row.id}>{group!==previousGroup&&<h3 className="today-group">{group}</h3>}<article key={row.id} id={`task-${row.id}`}><h3>{task.text}</h3><p>{task.dueDate?new Date(task.dueDate+"T12:00:00").toLocaleDateString("tr"):"Tarihsiz"} {task.dueTime}{task.priority==="important"?" · Önemli":""}{task.recurrence?" · "+recurrenceLabel(task.recurrence):""}</p><div className="actions"><button disabled={busy} onClick={()=>void complete(row)}>Tamamla</button><button onClick={()=>openForm("task",row)}>Ayrıntı</button></div><details><summary>Ertele</summary><div className="actions"><button disabled={busy} onClick={()=>void snooze(row,15)}>15 dakika</button><button disabled={busy} onClick={()=>void snooze(row,60)}>1 saat</button><button disabled={busy} onClick={()=>void snooze(row,1440)}>Yarın</button><button onClick={()=>openForm("task",row)}>Özel zaman</button></div></details></article></section>;})}<details><summary>Tamamlananlar</summary>{tasks.filter(row=>(row.data as PhoneTask).completed).map(row=><article key={row.id}><p>{(row.data as PhoneTask).text}</p><button disabled={busy} onClick={()=>void complete(row)}>Yeniden Aç</button></article>)}</details></>}{page==="notes"&&<NotesList syncLabel={busy?"Eşitleniyor…":state.queue.length?"Eşitleme bekliyor":"Güncel"} records={state.records} onNew={()=>openForm("note")} onOpen={row=>openForm("note",row)}/>}
    {page==="inbox"&&<><SendCard busy={busy} recording={recording} audio={audio} onOpen={openForm} onFile={file=>void upload(file,file.name)} onRecord={()=>recording?recorder.current?.stop():void startRecording()} onAudioSend={()=>{if(audio)void upload(audio,`Sesli-not.${audio.type.includes("mp4")?"m4a":audio.type.includes("ogg")?"ogg":"webm"}`);}} onAudioCancel={()=>setAudio(null)} /><h2 className="sent-history-title">Son gönderilenler</h2>{!inbox.length&&<p className="mobile-empty">Henüz gönderi yok.</p>}{inbox.map(item=><article key={item.id}><h3>{item.title}</h3><p>{item.handled?"İşlendi":"Bilgisayarda bekliyor"}</p>{item.kind==="file"?<p>{item.expiresAt&&item.expiresAt<Date.now()?"Dosyanın saklama süresi dolmuş.":`Saklama sonu: ${new Date(item.expiresAt!).toLocaleDateString("tr")}`}</p>:<p className="note-content">{item.content}</p>}</article>)}</>}
    {page==="work"&&<><p>Yalnızca bilgisayarda kayıtlı alanlar başlatılır. Çevrimdışı istekler 10 dakika sonra geçersiz olur.</p>{workspaces.map(workspace=><article key={workspace.id}><h3>{workspace.icon} {workspace.name}</h3><p>{workspace.description}</p><button disabled={busy} onClick={()=>void api<{offline:boolean}>(state,"commands",json({workspaceId:workspace.id,requestId:crypto.randomUUID()})).then(result=>setNotice(result.offline?"Bilgisayar çevrimdışı. İstek 10 dakika bekleyecek; bilgisayarda onay gerekir.":"İstek bilgisayara gönderildi.")).catch(e=>setError(e.message))}>Bilgisayarda Başlat</button></article>)}{!workspaces.length&&<p>Henüz eşitlenmiş çalışma alanı yok.</p>}</>}
    {page==="more"&&<><div className="more-list">{([{id:"work",label:"Çalışma Alanları",description:"Bilgisayardaki alanları başlat",icon:"folder"},{id:"subscriptions",label:"Abonelikler",description:"Düzenli ödemeler ve hatırlatmalar",icon:"archive"},{id:"settings",label:"Ayarlar",description:"Cihaz ve bildirim tercihleri",icon:"settings"}] as const).map(item=><button type="button" key={item.id} onClick={()=>changePage(item.id)}><span className="more-icon"><Icon name={item.icon} size={23}/></span><span><strong>{item.label}</strong><small>{item.description}</small></span><span aria-hidden="true">›</span></button>)}</div></>}
    {page==="subscriptions"&&<><div className="page-heading"><button className="primary-action" onClick={()=>setSubscriptionDraft(newSubscription())}>+ Ekle</button></div><div className="subscription-totals"><span>Aylık karşılık</span>{monthlyTotals(state.records.filter(r=>r.kind==="subscriptions"&&!r.deleted).map(r=>r.data as Subscription)).map(([c,a])=><strong key={c}>{money(a,c)}</strong>)}</div><p className="status">Dönem tutarlarının aylık ortalaması; para birimleri ayrı tutulur.</p>{state.records.filter(r=>r.kind==="subscriptions"&&!r.deleted).map(row=>{const sub=row.data as Subscription;return <article className="subscription-row" key={row.id}><div><h3>{sub.name}</h3><p>{money(sub.amount,sub.currency)} / {cycleLabel(sub)}</p><small>{sub.status==="active"?paymentLabel(sub):sub.status==="paused"?"Duraklatıldı":"İptal edildi"}</small></div><details className="overflow-menu"><summary aria-label={sub.name+" işlemleri"}>⋯</summary><div><button onClick={()=>setSubscriptionDraft(sub)}>Düzenle</button><button className="danger-action" disabled={busy} onClick={()=>{if(confirm("Yalnızca abonelik kaydı silinsin mi? Hizmet sağlayıcısındaki aboneliğiniz değişmez."))void saveMutation({mutationId:crypto.randomUUID(),kind:"subscriptions",id:row.id,baseVersion:row.version,data:null,deleted:true}).then(()=>setUndo({row,expires:Date.now()+10000})).catch(e=>setError(e.message));}}>Kaydı sil</button></div></details></article>;})}{!state.records.some(r=>r.kind==="subscriptions"&&!r.deleted)&&<p>İlk aboneliğini ekleyerek başla.</p>}</>}
    {page==="settings"&&<><section className="mobile-settings-card"><h2>Cihaz</h2><p>Eşleştirildi · {state.name}</p><form onSubmit={e=>{e.preventDefault();void api(state,"me",json({name})).then(()=>commit({...state,name})).then(()=>setNotice("Cihaz adı kaydedildi.")).catch(e=>setError(e.message));}}><label>Cihaz adı<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><button disabled={busy}>Kaydet</button></form></section><section className="mobile-settings-card"><h2>Bildirimler</h2><p>Bildirimler: {push?"Açık":typeof Notification!=="undefined"&&Notification.permission==="denied"?"İzin verilmedi":"Kapalı"}</p><button onClick={()=>void enablePush(state).then(()=>{setPush(true);setNotice("Bildirimler açıldı.");}).catch(e=>setError(e.message))}>Bildirimleri Aç</button><details><summary>Bildirim testi</summary><button onClick={()=>void api(state,"push/test",json({})).then(()=>setNotice("Test bildirimi gönderildi.")).catch(e=>setError(e.message))}>Test Bildirimi Gönder</button></details></section><section className="mobile-settings-card"><h2>Bağlantı ve gizlilik</h2><p>Görev, not ve abonelik bilgileri buluta eşitlenir; kart ve banka bilgisi saklanmaz. Çevrimdışı kayıtlar telefonda tutulur. İnternet döndüğünde eşitlenir. Bulut eşitleme ve Web Push için internet gerekir.</p><button className="disconnect-button" disabled={busy} onClick={()=>{if(state.queue.length||state.conflicts.length){setError("Eşitlenmemiş kayıtlar var. Önce eşitleyin.");return;}if(confirm("Telefon erişimi kaldırılsın mı? Buluttaki görev, not ve abonelikler silinmez."))void api<{id:string}>(state,"me").then(me=>api(state,"revoke",json({deviceId:me.id}))).then(async()=>{const registration=await navigator.serviceWorker.ready;await(await registration.pushManager.getSubscription())?.unsubscribe();await commit(emptyState());}).catch(e=>setError(e.message));}}>Cihaz Bağlantısını Kes</button></section></>}
    {state.conflicts.map((conflict,index)=><article key={index}><h3>Eşitleme çakışması</h3><p>Bu kayıt başka cihazda değişti. İki sürüm korundu.</p><p className="note-content">Yerel: {conflict.mutation.data ? "text" in conflict.mutation.data ? conflict.mutation.data.text : "name" in conflict.mutation.data ? conflict.mutation.data.name : conflict.mutation.data.title+" — "+conflict.mutation.data.content : "Silinmiş kayıt"}</p><p className="note-content">Bulut: {conflict.server?.data ? "text" in conflict.server.data ? conflict.server.data.text : "name" in conflict.server.data ? conflict.server.data.name : conflict.server.data.title+" — "+conflict.server.data.content : "Silinmiş kayıt"}</p><button disabled={busy} onClick={()=>{if(confirm("Bulut sürümü kullanılsın mı? Yerel değişiklik yalnızca bu kayıtta kaldırılır."))void commit({...state,conflicts:state.conflicts.filter((_,i)=>i!==index),records:conflict.server?[...state.records.filter(r=>r.id!==conflict.server!.id||r.kind!==conflict.server!.kind),conflict.server]:state.records}).catch(e=>setError(e.message));}}>Bulut sürümünü kullan</button><button disabled={busy} onClick={()=>{if(confirm("Yerel sürüm buluta gönderilsin mi?")){const mutation={...conflict.mutation,mutationId:crypto.randomUUID(),baseVersion:conflict.server?.version??0};const next={...state,conflicts:state.conflicts.filter((_,i)=>i!==index),queue:[...state.queue,mutation]};void commit(next).then(()=>refresh(next)).catch(e=>setError(e.message));}}}>Yerel sürümü gönder</button></article>)}
    </div>
    {subscriptionDraft&&<section ref={subscriptionEditorRef} className="editor" role="dialog" aria-modal="true" aria-label="Abonelik düzenle"><div><SubscriptionForm key={subscriptionDraft.id} initial={subscriptionDraft} busy={busy} onCancel={()=>setSubscriptionDraft(null)} onSave={async sub=>{const row=state.records.find(r=>r.kind==="subscriptions"&&r.id===sub.id);await saveMutation({mutationId:crypto.randomUUID(),kind:"subscriptions",id:sub.id,baseVersion:row?.version??0,data:sub,deleted:false});setSubscriptionDraft(null);}}/></div></section>}
    {undo&&undo.expires>Date.now()&&<div className="undo-toast" role="status">Kayıt silindi<button disabled={busy} onClick={()=>{const row=state.records.find(r=>r.kind===undo.row.kind&&r.id===undo.row.id);void saveMutation({mutationId:crypto.randomUUID(),kind:undo.row.kind,id:undo.row.id,baseVersion:row?.version??undo.row.version+1,data:undo.row.data,deleted:false}).then(()=>setUndo(null)).catch(e=>setError(e.message));}}>Geri al</button></div>}
    {notice&&<div className="mobile-toast" role="status">{notice}</div>}
    {form==="note"&&<section ref={editorRef} className="editor note-editor" role="dialog" aria-modal="true" aria-labelledby="editor-title"><NoteEditor title={title} content={content} onTitle={setTitle} onContent={setContent} onClose={closeForm} onSubmit={event=>void submit(event)} busy={busy} error={error} updatedAt={(editing?.data as PhoneNote|undefined)?.updatedAt} onDelete={editing?()=>{if(confirm("Bu not silinsin mi?"))void saveMutation({mutationId:crypto.randomUUID(),kind:"notes",id:editing.id,baseVersion:editing.version,data:null,deleted:true}).then(()=>{setUndo({row:editing,expires:Date.now()+10000});setForm(null);}).catch(e=>setError(e.message));}:undefined}/></section>}{form&&form!=="note"&&<section ref={editorRef} className="editor" role="dialog" aria-modal="true" aria-labelledby="editor-title"><div><div className="editor-heading"><h2 id="editor-title">{form==="task"?"Görev":form==="link"?"Link Gönder":form==="ai_prompt"?"ACK AI'a Mesaj Bırak":"Metin Gönder"}</h2><button type="button" aria-label="Düzenleyiciyi kapat" onClick={()=>setForm(null)}>×</button></div><form onSubmit={submit}>{(form==="task")&&<label>{form==="task"?"Görev metni":"Başlık"}<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} required={form==="task"} maxLength={form==="task"?2000:200}/></label>}{form!=="task"&&<label>{form==="link"?"Web adresi":"İçerik"}<textarea autoFocus value={content} onChange={e=>setContent(e.target.value)} required maxLength={20000}/></label>}{form==="task"&&<><label>Tarih<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Saat<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><RecurrenceFields key={editing?.id??"new"} value={recurrence} date={date} time={time} onChange={setRecurrence}/><details><summary>Öncelik</summary><label className="toggle"><input type="checkbox" checked={important} onChange={e=>setImportant(e.target.checked)}/>Önemli</label></details><label className="toggle"><input type="checkbox" checked={reminder} disabled={!date||!time} onChange={e=>setReminder(e.target.checked)}/>Hatırlat</label></>}<div className="actions"><button disabled={busy}>{form==="task"?"Kaydet":"Gönder"}</button><button type="button" onClick={()=>setForm(null)}>İptal</button>{editing&&<button type="button" disabled={busy} onClick={()=>{if(confirm("Bu kayıt silinsin mi?"))void saveMutation({mutationId:crypto.randomUUID(),kind:editing.kind,id:editing.id,baseVersion:editing.version,data:null,deleted:true}).then(()=>{setUndo({row:editing,expires:Date.now()+10000});setForm(null);}).catch(e=>setError(e.message));}}>Kaydı Sil</button>}</div>{error&&<p role="alert" className="error">{error}</p>}</form></div></section>}
    <MobileNav page={page} onChange={changePage} />
  </main>;
}
if("serviceWorker" in navigator)void navigator.serviceWorker.register("/sw.js").catch(()=>{});
createRoot(document.getElementById("root")!).render(<App/>);
