import { useEffect, useState } from "react";
import { Icon } from "./Icon";
import { prepareAudioDuration, restoreAudioStart } from "../../shared/audio";
type SendKind = "text" | "link" | "ai_prompt";
type Choice = SendKind | "file" | "audio";
export function SendCard({busy,recording,audio,file,feedback,onOpen,onSelectFile,onFile,onRecord,onAudioSend,onAudioCancel}:{busy:boolean;recording:boolean;audio:Blob|null;file:File|null;feedback:string;onOpen:(kind:SendKind)=>void;onSelectFile:(file:File|null)=>void;onFile:(file:File)=>Promise<boolean>;onRecord:()=>void;onAudioSend:()=>void;onAudioCancel:()=>void}) {
  const [kind,setKind]=useState<Choice|null>(()=>audio?"audio":file?"file":null),[preview,setPreview]=useState("");
  useEffect(()=>{if(!audio){setPreview("");return;}const url=URL.createObjectURL(audio);setPreview(url);return()=>URL.revokeObjectURL(url);},[audio]);
  const options:[Choice,string,string,"note"|"link"|"files"|"mic"|"spark"][]=[["text","Metin","Kısa bir mesaj","note"],["link","Link","Bir web adresi","link"],["file","Fotoğraf / Dosya","Seç ve gönder","files"],["audio","Sesli not","Kaydet ve dinle","mic"],["ai_prompt","ACK AI","Mesaj bırak","spark"]];
  return <section className="send-card" aria-labelledby="send-card-title"><div className="send-card-heading"><h2 id="send-card-title">Bilgisayarına gönder</h2><p>İçerik türünü seç, hazır olduğunda gönder.</p></div>
    {feedback&&<p className="send-success" role="status">✓ {feedback}</p>}
    <div className="send-grid">{options.map(([value,label,hint,icon])=><button key={value} className={kind===value?"selected":""} type="button" aria-pressed={kind===value} disabled={busy||recording} onClick={()=>{setKind(value);if(value!=="file"&&value!=="audio")onOpen(value);}}><span className="send-icon"><Icon name={icon}/></span><strong>{label}</strong><small>{hint}</small></button>)}</div>
    {kind==="file"&&<div className="send-file-panel"><label>Fotoğraf veya dosya<input type="file" accept="image/png,image/jpeg,image/webp,image/heic,application/pdf,audio/mp4,audio/mpeg,audio/ogg,audio/webm,audio/wav,text/plain" disabled={busy} onChange={event=>{onSelectFile(event.target.files?.[0]??null);event.target.value="";}}/></label>{file&&<><p className="send-file-name"><strong>{file.name}</strong><span>{Math.ceil(file.size/1024)} KB</span></p><div className="actions"><button type="button" className="primary-action" disabled={busy} onClick={()=>void onFile(file).then(ok=>{if(ok)onSelectFile(null);})}>{busy?"Gönderiliyor…":"Dosyayı gönder"}</button><button type="button" disabled={busy} onClick={()=>onSelectFile(null)}>Vazgeç</button></div></>}</div>}
    {kind==="audio"&&<div className="send-audio-panel">{!audio&&<button type="button" className={"send-record-button "+(recording?"recording":"")} disabled={busy} onClick={onRecord}><Icon name="mic"/><span><strong>{recording?"Kaydı durdur":"Kaydı başlat"}</strong><small>{recording?"Kayıt sürüyor · En fazla 2 dakika":"Göndermeden önce dinleyebilirsin"}</small></span><span aria-hidden="true">{recording?"■":"●"}</span></button>}{audio&&<div className="send-audio-preview"><p>Sesli not hazır · {Math.ceil(audio.size/1024)} KB</p>{preview&&<audio controls preload="metadata" src={preview} onLoadedMetadata={event=>prepareAudioDuration(event.currentTarget)} onDurationChange={event=>restoreAudioStart(event.currentTarget)} onSeeked={event=>restoreAudioStart(event.currentTarget)}/>}<div className="actions"><button type="button" className="primary-action" disabled={busy} onClick={onAudioSend}>{busy?"Gönderiliyor…":"Sesli notu gönder"}</button><button type="button" disabled={busy} onClick={onAudioCancel}>Vazgeç</button></div></div>}</div>}
    <p className="send-card-hint">En fazla 10 MB · Bulutta 30 gün. İçerik bilgisayarda kendiliğinden açılmaz. Başarısız gönderimde taslağın korunur.</p>
  </section>;
}
