import { ActionMenu } from "./ActionMenu";
import { useEffect, useState } from "react";
import { openUrl } from "@tauri-apps/plugin-opener";
import { downloadPhoneFile, phoneRequest } from "../phoneClient";
import { validUrl } from "../../shared/phone";
type Inbox={id:string;kind:string;title:string;content:string;mime:string|null;size:number|null;expiresAt:number|null;handled:number;createdAt:number};
export function PhoneInbox({onAiDraft}:{onAiDraft:(text:string)=>void}){
  const [items,setItems]=useState<Inbox[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function refresh(){setBusy(true);try{setItems((await phoneRequest<{items:Inbox[]}>("inbox")).items);setError("");}catch{setError("Telefon gelenleri alınamadı. Entegrasyonu ve internet bağlantısını kontrol edin.");}finally{setBusy(false);}}
  useEffect(()=>{void refresh();},[]);
  async function action(fn:()=>Promise<unknown>){setBusy(true);try{await fn();setError("");}catch(error){setError(error instanceof Error?error.message:"Gönderi işlemi tamamlanamadı.");}finally{setBusy(false);}}
  return <section className="hub-page"><header className="feature-heading section-heading"><div><h1>Gelenler</h1><p>Telefondan bıraktığınız içerikler. Dosyalar veya bağlantılar kendiliğinden açılmaz.</p></div><button className="button button-secondary" disabled={busy} onClick={()=>void refresh()}>Yenile</button></header>{error&&<p className="feedback error" role="alert">{error}</p>}{!items.length&&!error&&<p>Gelenler henüz boş.</p>}{items.map(item=><article className="surface hub-card" key={item.id}><h2>{item.title}</h2><p>{new Date(item.createdAt).toLocaleString("tr-TR")} · {item.handled?"İşlendi":"Bekliyor"}</p>{item.kind==="file"?<p>{item.size?`${Math.ceil(item.size/1024)} KB · `:""}{item.expiresAt&&item.expiresAt<Date.now()?"Dosyanın saklama süresi dolmuş.":`Saklama sonu: ${new Date(item.expiresAt!).toLocaleString("tr-TR")}`}</p>:<p className="phone-inbox-content">{item.content}</p>}<div className="hub-actions">{item.kind==="file"?<button disabled={busy||!!item.expiresAt&&item.expiresAt<Date.now()} onClick={()=>void action(()=>downloadPhoneFile(item.id,item.title))}>Bilgisayara Kaydet</button>:<><button disabled={busy} onClick={()=>void action(()=>navigator.clipboard.writeText(item.content))}>{item.kind==="link"?"Linki Kopyala":"Metni Kopyala"}</button>{item.kind==="link"&&validUrl(item.content)&&<button disabled={busy} onClick={()=>void action(()=>openUrl(item.content))}>Bağlantıyı Aç</button>}{item.kind==="ai_prompt"&&<button disabled={busy} onClick={()=>onAiDraft(item.content)}>ACK AI'da Aç</button>}</>}<ActionMenu label={item.title+" işlemleri"}><button disabled={busy} onClick={()=>void action(async()=>{await phoneRequest("handled",{id:item.id});setItems(items.map(row=>row.id===item.id?{...row,handled:1}:row));})}>İşlendi Olarak İşaretle</button><button className="danger-action" disabled={busy} onClick={()=>{if(window.confirm("Bu gelen buluttan silinsin mi? Bilgisayara kaydedilmiş dosyalar silinmez."))void action(async()=>{await phoneRequest("delete_inbox",{id:item.id});setItems(items.filter(row=>row.id!==item.id));});}}>Bulut Kaydını Sil</button></ActionMenu></div></article>)}</section>;
}
