import { ActionMenu } from "./ActionMenu";
import { useEffect, useRef, useState } from "react";
import { PHONE_WORKER_URL } from "../phoneDeployment";
import { toDataURL } from "qrcode";
import { configurePhone, phoneRequest, phoneStatus, type PhoneStatus } from "../phoneClient";
import { readPhoneSync, resolvePhoneConflict, synchronizePhone } from "../phoneSync";
type Device={id:string;name:string;lastSeen:number;notifications:number|null};
export function PhoneSettings(){
  const [status,setStatus]=useState<PhoneStatus|null>(null),[url,setUrl]=useState(""),[feedback,setFeedback]=useState(""),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[devices,setDevices]=useState<Device[]>([]),[pair,setPair]=useState<{url:string;code:string;expiresAt:number}|null>(null),[qr,setQr]=useState(""),[remaining,setRemaining]=useState(0),[sync,setSync]=useState(()=>{try{return readPhoneSync();}catch{return null;}});
  const busyRef=useRef(false);
  useEffect(()=>{let active=true;void phoneStatus().then(value=>{if(active){setStatus(value);setUrl(value.url || PHONE_WORKER_URL);if(value.enabled)void phoneRequest<{devices:Device[]}>("devices").then(result=>active&&setDevices(result.devices)).catch(()=>{});}}).catch(()=>setFeedback("Telefon ayarları okunamadı."));const configured=()=>{void phoneStatus().then(value=>{if(active){setStatus(value);setUrl(value.url || PHONE_WORKER_URL);}}).catch(()=>{});};window.addEventListener("ack-phone-configured",configured);const refresh=()=>{try{setSync(readPhoneSync());}catch{setFeedback("Telefon eşitleme kaydı okunamadı. Mevcut veriler korunuyor.");}};window.addEventListener("ack-phone-sync-status",refresh);return()=>{active=false;window.removeEventListener("ack-phone-configured",configured);window.removeEventListener("ack-phone-sync-status",refresh);};},[]);
  useEffect(()=>{if(!pair)return;const update=()=>setRemaining(Math.max(0,Math.ceil((pair.expiresAt-Date.now())/1000)));update();const timer=setInterval(update,1000);return()=>clearInterval(timer);},[pair]);
  async function action(fn:()=>Promise<void>){if(busyRef.current)return;busyRef.current=true;setBusy(true);setFeedback("");try{await fn();}catch(error){setFeedback(error instanceof Error?error.message:"Telefon işlemi tamamlanamadı.");}finally{busyRef.current=false;setBusy(false);}}
  async function enable(){await configurePhone(url.trim(),true);window.localStorage.removeItem("ack-deck.phone-restore-review.v1");const next=await phoneStatus();setStatus(next);setConfirm(false);window.dispatchEvent(new Event("ack-phone-configured"));setFeedback("Telefon entegrasyonu etkinleştirildi. Eşitleme başlatılıyor.");}
  return <section className="settings-card surface local-settings"><h2>Telefon</h2><p className="task-hint">Telefon bağlantısı: {status?.enabled?"Açık":"Kapalı"}</p><section className="settings-subsection" aria-label="Bağlantı adresi"><label className="archive-field">Telefon bağlantı adresi<input type="url" value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://ack-deck-phone.…workers.dev" disabled={busy||status?.enabled}/></label><p className="task-hint">Mevcut telefon bağlantısı bu adresi kullanır. Eşleştirilmiş telefonunu kullanmak için adresi değiştirmen gerekmez.</p></section>
    <section className="settings-subsection"><h3>Bulutta tutulanlar ve gizlilik</h3><p className="task-hint">Görevler, tekrar kuralları, abonelik ad/tutar/para birimi/yenileme/hatırlatma bilgileri, notlar, telefon gelenleri, hatırlatma zamanları, eşleştirilmiş cihazlar ve çalışma alanlarının yalnızca ad/kimlik/açıklamaları eşitlenir.</p><p className="task-hint">Gemini anahtarı, ACK AI sohbet geçmişi, dosya/klasör ve program yolları, Credential Manager verileri, arşiv ve diğer bilgisayar dosyaları gönderilmez. Telefon dosyaları yalnızca siz gönderdiğinizde 30 gün saklanır.</p><p className="task-hint">Bilgisayar kapalıyken telefon görevleri/notları ve bulut hatırlatmaları çalışır. Bulut eşitleme ve bildirim için internet gerekir. Windows hatırlatmaları mevcut davranışını korur.</p></section>
    <div className="settings-actions">{!status?.enabled?<button className="button button-secondary" disabled={busy||!status?.configured} onClick={()=>setConfirm(true)}>Telefon entegrasyonunu etkinleştir</button>:<><button className="button button-secondary" disabled={busy} onClick={()=>void action(async()=>{const result=await phoneRequest<{url:string;code:string;expiresAt:number}>("pair");setPair(result);setQr(await toDataURL(result.url,{width:256,margin:2}));})}>Telefon Eşleştir</button><ActionMenu label="Telefon işlemleri"><button className="button button-secondary" disabled={busy} onClick={()=>void action(async()=>{await synchronizePhone();setSync(readPhoneSync());setFeedback("Eşitleme tamamlandı.");})}>Senkronizasyonu şimdi çalıştır</button><button className="button button-secondary" disabled={busy} onClick={()=>void action(async()=>{await configurePhone(status.url,false);setStatus(await phoneStatus());window.dispatchEvent(new Event("ack-phone-configured"));setPair(null);setDevices([]);setFeedback("Entegrasyon duraklatıldı. Yerel ve bulut kayıtları silinmedi.");})}>Telefon entegrasyonunu duraklat</button><button className="button button-secondary" disabled={busy} onClick={()=>void action(async()=>{await phoneRequest("status");setDevices((await phoneRequest<{devices:Device[]}>("devices")).devices);setFeedback("Telefon sunucusu hazır.");})}>Bağlantıyı ve cihazları kontrol et</button></ActionMenu></>}</div>
    {confirm&&<div className="backup-confirm"><h3>Görev, not ve abonelikler buluta eşitlensin mi?</h3><p>Mevcut görev, not ve abonelik bilgileri Cloudflare sunucunuzda tutulacak. Ödeme kartı veya banka bilgisi saklanmaz. İlk yükleme bu onaydan sonra başlar. Gemini anahtarı ve bilgisayar yolları gönderilmez. Yerel silmeler buluta da yansır; aynı kayıttaki eşzamanlı değişiklikler seçim yapmanız için korunur. Yedek geri yüklediyseniz kayıtlarınızı önce kontrol edin.</p><button className="button button-primary" disabled={busy} onClick={()=>void action(enable)}>Onayla ve Etkinleştir</button><button className="button button-secondary" onClick={()=>setConfirm(false)}>İptal</button></div>}
    {pair&&<div className="phone-pair"><h3>Telefon Eşleştir</h3>{remaining>0?<><img src={qr} alt="ACKDeck Mobile eşleştirme QR kodu"/><p>{remaining} saniye kaldı. Kod tek kullanımlıktır.</p><label className="archive-field">Alternatif eşleştirme kodu<input readOnly value={pair.code}/></label><p>iPhone'da ACKDeck Mobile'ı Ana Ekrana ekleyip açın ve bu kodu girin. Ardından Bildirimleri Aç'ı seçin.</p></>:<p>Eşleştirme kodunun süresi doldu. Yeni kod oluşturun.</p>}</div>}
    <p className="task-hint">Son senkronizasyon: {sync?.lastSync?new Date(sync.lastSync).toLocaleString("tr-TR"):"Henüz yapılmadı"}</p><h3>Eşleştirilmiş cihazlar</h3>{devices.length?devices.map(device=><div className="phone-device" key={device.id}><div><strong>{device.name}</strong><p>Son erişim: {new Date(device.lastSeen).toLocaleString("tr-TR")} · Bildirimler: {device.notifications?"Açık":"Kapalı"}</p></div><button className="button button-secondary" disabled={busy} onClick={()=>{if(window.confirm(`${device.name} cihazının erişimi kaldırılsın mı? Görev ve notlar silinmez.`))void action(async()=>{await phoneRequest("revoke",{deviceId:device.id});setDevices(devices.filter(row=>row.id!==device.id));});}}>Erişimi Kaldır</button></div>):<p className="task-hint">Görüntülenen eşleştirilmiş cihaz yok.</p>}
    {sync?.conflicts.map((conflict,index)=><div className="backup-confirm" key={index}><h3>Eşitleme çakışması</h3><p>Yerel ve bulut sürümleri korundu. {conflict.local.data&&"text" in conflict.local.data?conflict.local.data.text:conflict.local.data&&"title" in conflict.local.data?conflict.local.data.title:conflict.local.data&&"name" in conflict.local.data?conflict.local.data.name:"Silinmiş kayıt"}</p><button className="button button-secondary" disabled={busy} onClick={()=>{if(window.confirm("Bu kayıtta bulut sürümü kullanılsın mı?"))void action(async()=>{await resolvePhoneConflict(index,true);setSync(readPhoneSync());});}}>Bulut sürümünü kullan</button><button className="button button-secondary" disabled={busy} onClick={()=>{if(window.confirm("Bu kaydın yerel sürümü buluta gönderilsin mi?"))void action(async()=>{await resolvePhoneConflict(index,false);await synchronizePhone();setSync(readPhoneSync());});}}>Yerel sürümü gönder</button></div>)}
    {feedback&&<p className="feedback" role="status">{feedback}</p>}
  </section>;
}
