import { EditorDialog } from "./EditorDialog";
import { ActionMenu } from "./ActionMenu";
import { offerUndo } from "../recordUndo";
import { useEffect, useState } from "react";
import { loadShortcuts, saveShortcuts, removeShortcut, pickTarget, saveUrl, type Shortcut, type SavedTarget } from "../workHubStore";
import { launchShortcut, revealShortcut } from "../hubLaunch";
import { invoke } from "@tauri-apps/api/core";
import type { FileStatus } from "../fileStore";
import { normalizeHub, updateUsage, usageFor } from "../usageStore";
const labels = { file: "Dosya", folder: "Klasör", url: "Web Adresi", application: "Uygulama" };
export function Shortcuts({ initialId }: { initialId?: string }) {
  const [loaded, setLoaded] = useState(loadShortcuts), [draft, setDraft] = useState<Shortcut | null>(() => loadShortcuts().entries.find(v => v.id === initialId) ?? null), [query, setQuery] = useState(""), [url, setUrl] = useState("");
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), [removing, setRemoving] = useState<string | null>(null);
  const [replacementUrl, setReplacementUrl] = useState(() => loadShortcuts().entries.find(v => v.id === initialId)?.target ?? "");
  const [statuses, setStatuses] = useState<FileStatus[]>([]);
  useEffect(() => { let active = true; const items = loaded.entries.filter(v => v.type === "file" || v.type === "folder").map(v => ({ path: v.target, kind: v.type })); if (items.length) void invoke<FileStatus[]>("check_file_entries", { items }).then(value => { if (active) setStatuses(value); }).catch(() => { if (active) setStatuses([]); }); else setStatuses([]); return () => { active = false; }; }, [loaded.entries]);
  function commit(entries: Shortcut[]) { if (!saveShortcuts(entries)) { setError("Kısayol kaydedilemedi. Mevcut kayıtlar korunuyor."); return false; } setLoaded(loadShortcuts()); setError(""); return true; }
  useEffect(() => { const refresh = () => setLoaded(loadShortcuts()); window.addEventListener("ack-data-changed", refresh); return () => window.removeEventListener("ack-data-changed", refresh); }, []);
  async function add(kind: SavedTarget["kind"]) { if (busy) return; setBusy(true); setError(""); try { const saved = kind === "url" ? await saveUrl(url) : await pickTarget(kind); if (saved) { const item: Shortcut = { id: crypto.randomUUID(), name: saved.name.slice(0, 160), type: saved.kind, target: saved.target, savedId: saved.id, description: "", pinned: false, lastUsedAt: 0, useCount: 0 }; if (commit([...loadShortcuts().entries, item])) { setDraft(item); setReplacementUrl(item.target); setUrl(""); } } } catch { setError(kind === "url" ? "Geçerli bir http veya https adresi girin." : "Öğe seçilemedi. Uygulamalar için bir .exe seçin; komut ve betik çalıştırıcıları desteklenmez."); } finally { setBusy(false); } }
  async function open(id: string) { if (busy) return; setBusy(true); setError(""); try { await launchShortcut(id); setLoaded(loadShortcuts()); } catch { setError("Kısayol açılamadı. Dosya, klasör veya uygulama bulunamıyor olabilir."); } finally { setBusy(false); } }
  async function replaceTarget() {
    if (!draft || busy) return; setBusy(true); setError("");
    try { const saved = draft.type === "url" ? await saveUrl(replacementUrl) : await pickTarget(draft.type); if (saved) { const { legacy: _, ...current } = draft; setDraft({ ...current, target: saved.target, savedId: saved.id }); setReplacementUrl(saved.target); } }
    catch { setError(draft.type === "url" ? "Geçerli bir http veya https adresi girin." : "Hedef seçilemedi. Mevcut kısayol değişmedi."); }
    finally { setBusy(false); }
  }
  const entries = loaded.entries.filter(v => normalizeHub(v.name + " " + v.target + " " + v.description).includes(normalizeHub(query))).sort((a, b) => Number(usageFor("shortcuts", b.id).pinned) - Number(usageFor("shortcuts", a.id).pinned) || b.lastUsedAt - a.lastUsedAt);
  return <section className="hub-page"><div className="section-heading"><div><h1>Kısayollar</h1><p>Tek bir dosya, klasör, uygulama veya web adresine hızlıca eriş.</p></div></div>
    {(error || loaded.error) && <p role="alert" className="tool-feedback">{error || loaded.error}</p>}
    <details className="advanced-fields"><summary>+ Kısayol ekle</summary><div className="hub-actions">{([['file', 'Dosya Ekle'], ['folder', 'Klasör Ekle'], ['application', 'Uygulama Ekle']] as const).map(([kind, label]) => <button className="button button-secondary" key={kind} type="button" disabled={busy || loaded.locked} onClick={() => void add(kind)}>{label}</button>)}</div>
    <div className="hub-actions"><label>Web adresi<input type="url" placeholder="https://..." maxLength={4096} value={url} onChange={e => setUrl(e.target.value)} /></label><button type="button" disabled={busy || loaded.locked || !url} onClick={() => void add("url")}>Web Adresi Ekle</button></div>
    </details><label>Kısayol ara<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Ad, açıklama veya yol..." maxLength={200} /></label>
    {draft && <EditorDialog title="Kısayolu düzenle" onClose={() => setDraft(null)} busy={busy} error={error}><form className="surface hub-editor" onKeyDown={e => { if (e.key === "Escape") setDraft(null); }} onSubmit={e => { e.preventDefault(); if (draft.type === "url" && replacementUrl !== draft.target) { setError("Yeni web adresini önce Hedefi Güncelle ile doğrulayın."); return; } if (commit(loadShortcuts().entries.map(v => v.id === draft.id ? draft : v))) setDraft(null); }}><label>Görünen ad<input autoFocus required maxLength={160} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>Açıklama<input maxLength={2000} value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><p className="hub-path" title={draft.target}>{draft.target}</p>{draft.type === "url" && <label>Yeni web adresi<input type="url" maxLength={4096} value={replacementUrl} onChange={e => setReplacementUrl(e.target.value)} /></label>}<button type="button" disabled={busy || (draft.type === "url" && !replacementUrl.trim())} onClick={() => void replaceTarget()}>{draft.type === "url" ? "Hedefi Güncelle" : "Hedefi Yeniden Seç"}</button><small>Yalnızca kısayolun bağlantısı değişir; gerçek öğeler değiştirilmez.</small><div className="hub-actions"><button className="button button-primary" disabled={busy || !draft.name.trim()}>Kaydet</button><button type="button" onClick={() => setDraft(null)}>İptal</button></div></form></EditorDialog>}
    <div className="hub-grid">{entries.map(item => <article className="surface hub-card" key={item.id}><h2>{item.name}</h2><small>{labels[item.type]}</small><p>{item.description}</p><p className="hub-path" title={item.target}>{item.target}</p>{statuses.find(v => v.path === item.target)?.state === "missing" && <small className="overdue">Bulunamadı</small>}{statuses.find(v => v.path === item.target)?.metadata?.sizeBytes != null && <small>{(statuses.find(v => v.path === item.target)!.metadata!.sizeBytes! / 1024).toLocaleString("tr-TR", { maximumFractionDigits: 1 })} KB</small>}<div className="hub-actions"><button className="button button-primary" type="button" disabled={busy} onClick={() => void open(item.id)}>Aç</button><ActionMenu label={item.name+" işlemleri"}><button type="button" disabled={busy || loaded.locked} onClick={() => { const pinned = !usageFor("shortcuts", item.id).pinned; if (updateUsage("shortcuts", item.id, pinned)) commit(loadShortcuts().entries.map(v => v.id === item.id ? { ...v, pinned } : v)); else setError("Sabitleme kaydedilemedi."); }}>{usageFor("shortcuts", item.id).pinned ? "Sabitlemeyi Kaldır" : "Sabitle"}</button><button type="button" disabled={busy || loaded.locked} onClick={() => { setDraft(item); setReplacementUrl(item.target); }}>Düzenle</button>{(item.type === "file" || item.type === "folder") && <button type="button" disabled={busy} onClick={() => { setBusy(true); void revealShortcut(item.id).catch(() => setError("Öğe Explorer’da gösterilemedi. Konumu kontrol edin.")).finally(() => setBusy(false)); }}>Explorer’da Göster</button>}<button type="button" onClick={() => setRemoving(item.id)}>Listeden Kaldır</button><button type="button" onClick={() => void navigator.clipboard.writeText(item.target).catch(() => setError("Yol kopyalanamadı."))}>Yolu Kopyala</button></ActionMenu></div></article>)}</div>
    {!entries.length && <p className="dashboard-empty">{query ? "Eşleşen kısayol bulunamadı." : "Henüz kısayol eklenmedi."}</p>}
    {removing && <div className="surface hub-editor" role="alertdialog" aria-label="Kısayolu kaldır"><p>Yalnızca ACKDeck kaydı kaldırılacak. Gerçek dosya, klasör veya uygulama silinmez.</p><button type="button" onClick={() => { const removed = loadShortcuts().entries.find(v => v.id === removing); if (removeShortcut(removing)) { if (removed) offerUndo({ source: "shortcuts", record: removed }); setLoaded(loadShortcuts()); setRemoving(null); setDraft(null); } else setError("Kayıt kaldırılamadı. Veriler korunuyor."); }}>Listeden Kaldır</button><button type="button" onClick={() => setRemoving(null)}>İptal</button></div>}
  </section>;
}
