import { ChecklistEditor } from "../../shared/ChecklistEditor";
import { RecordLinkFields } from "./RecordLinkFields";
import { RELEASE_TEMPLATE,loadTemplates,templateTask,saveTemplate } from "../templateStore";
import { parseSmartCapture } from "../../shared/smartCapture";
import { loadProjectSnapshot } from "../projectStore";
import { moveBefore, moveTo } from "../reorder";
import { EditorDialog } from "./EditorDialog";
import { ActionMenu } from "./ActionMenu";
import { RecurrenceFields } from "../../shared/RecurrenceFields";
import { completeOccurrence, nextOccurrence, recurrenceLabel, scheduleDate } from "../../shared/recurrence";
import { offerUndo } from "../recordUndo";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Icon } from "./Icon";
import { filterTasks, loadTasks, localDateKey, saveTasks, taskDueAt, type Task, type TaskFilter } from "../taskStore";
const filters: [TaskFilter, string][] = [["all", "Aktif"], ["today", "Bugün"], ["upcoming", "Yaklaşan"], ["undated", "Tarihsiz"], ["completed", "Tamamlanan"]];
export function Tasks({ fullPage = false, initialId, focusNew = false, initialDate }: { fullPage?: boolean; initialId?: string; focusNew?: boolean; initialDate?: string }) {
  const [loaded, setLoaded] = useState(loadTasks);
  const [tasks, setTasks] = useState<Task[]>(loaded.entries), [error, setError] = useState(loaded.warning ?? "");
  const [dragged,setDragged]=useState<string|null>(null);
  const [draft, setDraft] = useState(""), [editor, setEditor] = useState<Task | null>(null);
  const [templateName,setTemplateName]=useState<string|null>(null),[templateFeedback,setTemplateFeedback]=useState("");
  const editorOriginal = useRef<Task | null>(null);
  useEffect(()=>{setTemplateName(null);setTemplateFeedback("");editorOriginal.current=editor?loadTasks().entries.find(t=>t.id===editor.id)??null:null;},[editor?.id]);
  const [filter, setFilter] = useState<TaskFilter>(() => initialId && loadTasks().entries.some(task => task.id === initialId && task.completed) ? "completed" : "all"), [deleteId, setDeleteId] = useState<string | null>(null);
  useEffect(() => { const refresh = () => { const value = loadTasks(); setLoaded(value); setTasks(value.entries); if (value.warning) setError(value.warning); }; window.addEventListener("ack-data-changed", refresh); return () => window.removeEventListener("ack-data-changed", refresh); }, []);
  useEffect(() => { if (initialDate) setEditor({...newTask(""),dueDate:initialDate}); if (focusNew) document.getElementById("new-task")?.focus(); if (initialId) document.getElementById("task-" + initialId)?.scrollIntoView({ block: "center" }); }, [focusNew, initialId]);
  function commit(next: Task[]) { if (!saveTasks(next, loadTasks())) { setError("Görevler kaydedilemedi. Mevcut veriler korunuyor."); return false; } setTasks(next); setError(""); return true; }
  function snooze(task:Task,minutes:number){const until=Date.now()+minutes*60000;commit(loadTasks().entries.map(t=>t.id===task.id?{...t,reminder:true,snoozedUntil:until,occurrenceAt:t.recurrence?t.occurrenceAt??taskDueAt(t):null,remindedFor:null}:t));}
  function newTask(text: string): Task { return { id: crypto.randomUUID(), text, completed: false, dueDate: null, dueTime: null, priority: "normal", reminder: false }; }
  function addTask(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const text = draft.trim(); if (!text || loaded.locked) return; const capture=parseSmartCapture(text,loadProjectSnapshot().entries); if(capture?.kind==="task"){const {kind:_,...fields}=capture;setEditor({...newTask(capture.text),...fields});return;} if(capture?.kind==="note"){setError("Bu bir not taslağı. ACK AI veya hızlı yakalama üzerinden not olarak oluşturabilirsiniz.");return;} if(commit([newTask(text), ...loadTasks().entries]))setDraft(""); }
  function saveEditor(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editor || !editor.text.trim()) return;
    if (editor.reminder && taskDueAt(editor) === null) { setError("Hatırlatma için geçerli bir tarih ve saat seçin."); return; }
    const current = loadTasks().entries; let updated = { ...editor, text: editor.text.trim() };
    const previous=current.find(t=>t.id===editor.id);
    const stable=(t:Task|null|undefined)=>{if(!t)return null;const {remindedFor:_,...value}=t;return JSON.stringify(value);};
    if(editorOriginal.current&&stable(previous)!==stable(editorOriginal.current)){setError("Bu görev başka bir cihazda değişti veya silindi. Taslağın burada korunuyor; güncel görevi yeniden açmadan kaydetme.");return;}
    if(editor.recurrence && (JSON.stringify(editor.recurrence)!==JSON.stringify(previous?.recurrence)||editor.dueDate!==previous?.dueDate||editor.dueTime!==previous?.dueTime)){if(!editor.dueDate||!editor.dueTime){setError("Tekrar için tarih ve saat seçin.");return;}const rule={...editor.recurrence,start:editor.dueDate,time:editor.dueTime};const first=nextOccurrence(rule,new Date(rule.start+"T00:00:00Z").getTime()-86400000);if(!first){setError("Tekrar günlerini ve bitişini kontrol edin.");return;}updated={...updated,recurrence:rule,occurrenceAt:first.at,dueDate:first.date,dueTime:rule.time,snoozedUntil:null,remindedFor:null,completed:false};}
    if(!editor.recurrence){updated={...updated,recurrence:null,...(previous?.recurrence||editor.dueDate!==previous?.dueDate||editor.dueTime!==previous?.dueTime?{occurrenceAt:null,snoozedUntil:null,remindedFor:null}:{})};}
    if (commit(current.some((task) => task.id === editor.id) ? current.map((task) => task.id === editor.id ? updated : task) : [updated, ...current])) { setEditor(null); setDraft(""); }
  }
  const remaining = tasks.filter((task) => !task.completed).length, shown = filterTasks(tasks, filter);
  return <section className={"section tasks-section " + (fullPage ? "tasks-page" : "")} aria-labelledby="tasks-heading">
    <div className="section-heading"><div>{!fullPage && <span className="eyebrow">GÜNÜN AKIŞI</span>}{fullPage ? <><h1 id="tasks-heading">Görevler</h1><p className="tasks-description">Yapılacaklarını planla, tamamladıklarını ayrı tut.</p></> : <h2 id="tasks-heading">Yapılacaklar</h2>}</div><span className="task-count">{remaining} KALDI</span></div>
    <div className="task-capture-row"><label className="task-template-picker"><span className="sr-only">Şablondan oluştur</span><select value="" onChange={e=>{const t=[RELEASE_TEMPLATE,...loadTemplates().entries].find(t=>t.id===e.target.value);if(t)setEditor(templateTask(t));}}><option value="">Şablon…</option>{[RELEASE_TEMPLATE,...loadTemplates().entries].map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><form className="task-form" onSubmit={addTask}><label className="sr-only" htmlFor="new-task">Hızlı görev ekle</label><Icon name="plus" size={18} /><input id="new-task" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Yapılacak bir şey yaz…" maxLength={160} disabled={loaded.locked} /><button type="submit" disabled={!draft.trim() || loaded.locked} aria-label="Görev ekle"><Icon name="arrowRight" size={17} /></button></form><button className="button button-primary task-create-button" type="button" title="Tarih ve hatırlatma ile yeni görev oluştur" onClick={() => { setEditor(newTask(draft)); setDeleteId(null); }} disabled={loaded.locked}><Icon name="plus" size={17}/>Yeni görev</button></div>
    <div className="tasks-card surface">
      <div className="task-filters" role="group" aria-label="Görev filtresi">{filters.map(([key, label]) => <button type="button" key={key} aria-pressed={filter === key} onClick={() => setFilter(key)}>{label}</button>)}</div>
      {error && <p className="tool-feedback error" role="alert">{error}</p>}
      {editor && <EditorDialog title={tasks.some(task => task.id === editor.id) ? "Görevi düzenle" : "Yeni görev"} description="Görev bilgilerini ve hatırlatmayı buradan düzenle." onClose={() => setEditor(null)} error={error}><form className="task-editor" onSubmit={saveEditor} onKeyDown={(event) => { if (event.key === "Escape") { event.preventDefault(); setEditor(null); } }} aria-label="Görev düzenleyici">
        <label className="archive-field">Görev<input autoFocus value={editor.text} onChange={(event) => setEditor({ ...editor, text: event.target.value })} maxLength={160} required /></label>
        <RecordLinkFields value={editor} onChange={patch=>setEditor({...editor,...patch})}/><ChecklistEditor value={editor.checklist} onChange={checklist=>setEditor({...editor,checklist})}/><div className="archive-form-grid"><label className="archive-field">{editor.recurrence ? "Başlangıç günü" : "Tarih"}<input type="date" value={editor.dueDate ?? ""} onChange={(event) => setEditor({ ...editor, dueDate: event.target.value || null, reminder: event.target.value ? editor.reminder : false })} /></label><label className="archive-field">Saat<input type="time" value={editor.dueTime ?? ""} onChange={(event) => setEditor({ ...editor, dueTime: event.target.value || null, reminder: event.target.value ? editor.reminder : false })} /></label></div><RecurrenceFields key={editor.id} value={editor.recurrence??null} date={editor.dueDate??""} time={editor.dueTime??""} onChange={recurrence=>setEditor({...editor,recurrence,...(recurrence?{dueDate:editor.dueDate||recurrence.start,dueTime:editor.dueTime||recurrence.time}:{})})}/><label className="reminder-toggle"><input type="checkbox" checked={editor.reminder ?? false} disabled={!editor.dueDate || !editor.dueTime} onChange={(event) => setEditor({ ...editor, reminder: event.target.checked })} />Hatırlatma</label>
        {editor.reminder&&<label className="archive-field">Ne zaman hatırlat?<select value={editor.reminderLeadMinutes??0} onChange={e=>setEditor({...editor,reminderLeadMinutes:Number(e.target.value)})}><option value="0">Görev saatinde</option><option value="15">15 dakika önce</option><option value="60">1 saat önce</option><option value="1440">1 gün önce</option>{editor.reminderLeadMinutes&&! [0,15,60,1440].includes(editor.reminderLeadMinutes)&&<option value={editor.reminderLeadMinutes}>{editor.reminderLeadMinutes} dakika önce</option>}</select></label>}<p className="task-hint">Windows bildirimleri ACKDeck çalışırken gönderilir. Telefon eşitlemesi ve bildirimler açıksa, bulut hatırlatmaları bilgisayar kapalıyken de sürer.</p>
        {templateName!==null&&<div className="task-template-save"><label className="archive-field">Şablon adı<input value={templateName} maxLength={100} onChange={e=>setTemplateName(e.target.value)}/></label><button type="button" className="button button-secondary" disabled={!templateName.trim()||!editor.text.trim()} onClick={()=>{if(saveTemplate({id:crypto.randomUUID(),name:templateName.trim(),text:editor.text,checklist:editor.checklist??[],projectId:editor.projectId,workspaceId:editor.workspaceId})){setTemplateName(null);setTemplateFeedback("Şablon saklandı.");}else setError("Şablon kaydedilemedi. En fazla 100 şablon saklanabilir.");}}>Şablonu kaydet</button><button type="button" className="button button-secondary" onClick={()=>setTemplateName(null)}>Vazgeç</button></div>}{templateFeedback&&<p role="status">{templateFeedback}</p>}<div className="settings-actions"><button type="button" className="button button-secondary" onClick={()=>{setTemplateName(editor.text.slice(0,100));setTemplateFeedback("");}}>Şablon olarak sakla</button><button className="button button-primary" type="submit">Kaydet</button><button className="button button-secondary" type="button" onClick={() => setEditor(null)}>Vazgeç</button></div>
      </form></EditorDialog>}
      <div className="task-list">{shown.length ? shown.map((task) => <div draggable={!loaded.locked} onDragStart={event=>{setDragged(task.id);event.dataTransfer.setData("text/plain",task.id);}} onDragOver={event=>{if(dragged)event.preventDefault();}} onDrop={event=>{event.preventDefault();if(dragged)commit(moveTo(loadTasks().entries,dragged,task.id));setDragged(null);}} onDragEnd={()=>setDragged(null)} id={"task-" + task.id} className={`task-item ${task.completed ? "completed" : ""} ${!task.completed && !task.recurrence && task.dueDate && task.dueDate < localDateKey() ? "overdue" : ""} ${initialId === task.id ? "record-highlight" : ""}`} key={task.id}>
        <button className="task-toggle" type="button" disabled={loaded.locked} onClick={() => commit(loadTasks().entries.map((item) => item.id === task.id ? completeOccurrence(item) : item))} aria-label={`${task.text}: ${task.completed ? "tamamlanmadı olarak işaretle" : "tamamlandı olarak işaretle"}`} aria-pressed={task.completed}>{task.completed && <Icon name="check" size={13} />}</button>
        <div className="task-text"><button className="task-open" type="button" disabled={loaded.locked} onClick={() => { setEditor({ ...task }); setDeleteId(null); }}><span>{task.text}</span>{!!task.checklist?.length&&<small className="checklist-progress">{task.checklist.filter(c=>c.completed).length}/{task.checklist.length} adım</small>}<small className="task-meta">{task.recurrence ? recurrenceLabel(task.recurrence) : task.dueDate ? task.dueDate.split("-").reverse().join(".") : "Tarihsiz"}{task.dueTime && " · " + task.dueTime}{!task.completed && !task.recurrence && task.dueDate && task.dueDate < localDateKey() && " · Tarihi geçti"}{task.recurrence && " · " + (scheduleDate(task)?.split("-").reverse().join(".") ?? "")}{task.snoozedUntil && " · Ertelendi"}</small></button>{deleteId === task.id && <div className="task-delete-confirm"><span>Bu görev silinsin mi?</span><button type="button" onClick={() => { if (commit(loadTasks().entries.filter((item) => item.id !== task.id))) { offerUndo({ source: "tasks", record: task }); setDeleteId(null); } }}>Evet, sil</button><button type="button" onClick={() => setDeleteId(null)}>Vazgeç</button></div>}</div>
        <ActionMenu label={task.text+" işlemleri"}><button type="button" disabled={loaded.locked||shown[0]?.id===task.id} onClick={()=>{const previous=shown[shown.indexOf(task)-1];if(previous)commit(moveBefore(loadTasks().entries,task.id,previous.id));}}>Yukarı taşı</button><button type="button" disabled={loaded.locked||shown[shown.length-1]?.id===task.id} onClick={()=>{const next=shown[shown.indexOf(task)+1];if(next)commit(moveBefore(loadTasks().entries,next.id,task.id));}}>Aşağı taşı</button>{task.dueDate&&task.dueTime&&!task.completed&&<><button type="button" onClick={()=>snooze(task,15)}>15 dakika ertele</button><button type="button" onClick={()=>snooze(task,60)}>1 saat ertele</button><button type="button" onClick={()=>snooze(task,1440)}>Yarın hatırlat</button></>}<button className="task-details-button" type="button" disabled={loaded.locked} aria-label={task.text + " görevini düzenle"} onClick={() => { setEditor({ ...task }); setDeleteId(null); }}>Düzenle</button><button className="task-delete" type="button" disabled={loaded.locked} onClick={() => setDeleteId(task.id)} aria-label={`${task.text} görevini sil`}><Icon name="trash" size={16} /> Sil</button></ActionMenu>
      </div>) : <div className="empty-tasks">{tasks.length ? "Bu filtrede görev yok." : loaded.locked ? "Görevler okunamadı. Mevcut veriler korunuyor." : "Henüz görev yok. Yukarıdan bir görev ekleyebilirsin."}</div>}</div>
      <div className="task-footer"><span className="task-footer-dot" /> {tasks.length} görevden {tasks.length - remaining} tanesi tamamlandı</div>
    </div></section>;
}
