import { EditorDialog } from "./EditorDialog";
import { ActionMenu } from "./ActionMenu";
import { RecurrenceFields } from "../../shared/RecurrenceFields";
import { completeOccurrence, nextOccurrence, recurrenceLabel } from "../../shared/recurrence";
import { offerUndo } from "../recordUndo";
import { useEffect, useState, type FormEvent } from "react";
import { Icon } from "./Icon";
import { filterTasks, loadTasks, localDateKey, saveTasks, taskDueAt, type Task, type TaskFilter } from "../taskStore";
const filters: [TaskFilter, string][] = [["all", "Aktif"], ["today", "Bugün"], ["upcoming", "Yaklaşan"], ["undated", "Tarihsiz"], ["completed", "Tamamlanan"]];
export function Tasks({ fullPage = false, initialId, focusNew = false }: { fullPage?: boolean; initialId?: string; focusNew?: boolean }) {
  const [loaded, setLoaded] = useState(loadTasks);
  const [tasks, setTasks] = useState<Task[]>(loaded.entries), [error, setError] = useState(loaded.warning ?? "");
  const [draft, setDraft] = useState(""), [editor, setEditor] = useState<Task | null>(null);
  const [filter, setFilter] = useState<TaskFilter>(() => initialId && loadTasks().entries.some(task => task.id === initialId && task.completed) ? "completed" : "all"), [deleteId, setDeleteId] = useState<string | null>(null);
  useEffect(() => { const refresh = () => { const value = loadTasks(); setLoaded(value); setTasks(value.entries); if (value.warning) setError(value.warning); }; window.addEventListener("ack-data-changed", refresh); return () => window.removeEventListener("ack-data-changed", refresh); }, []);
  useEffect(() => { if (focusNew) document.getElementById("new-task")?.focus(); if (initialId) document.getElementById("task-" + initialId)?.scrollIntoView({ block: "center" }); }, [focusNew, initialId]);
  function commit(next: Task[]) { if (!saveTasks(next, loadTasks())) { setError("Görevler kaydedilemedi. Mevcut veriler korunuyor."); return false; } setTasks(next); setError(""); return true; }
  function snooze(task:Task,minutes:number){const until=Date.now()+minutes*60000;commit(loadTasks().entries.map(t=>t.id===task.id?{...t,reminder:true,snoozedUntil:until,occurrenceAt:t.recurrence?t.occurrenceAt??taskDueAt(t):null,remindedFor:null}:t));}
  function newTask(text: string): Task { return { id: crypto.randomUUID(), text, completed: false, dueDate: null, dueTime: null, priority: "normal", reminder: false }; }
  function addTask(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const text = draft.trim(); if (text && !loaded.locked && commit([newTask(text), ...loadTasks().entries])) setDraft(""); }
  function saveEditor(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editor || !editor.text.trim()) return;
    if (editor.reminder && taskDueAt(editor) === null) { setError("Hatırlatma için geçerli bir tarih ve saat seçin."); return; }
    const current = loadTasks().entries; let updated = { ...editor, text: editor.text.trim() };
    const previous=current.find(t=>t.id===editor.id);
    if(editor.recurrence && (JSON.stringify(editor.recurrence)!==JSON.stringify(previous?.recurrence)||editor.dueDate!==previous?.dueDate||editor.dueTime!==previous?.dueTime)){if(!editor.dueDate||!editor.dueTime){setError("Tekrar için tarih ve saat seçin.");return;}const rule={...editor.recurrence,start:editor.dueDate,time:editor.dueTime};const first=nextOccurrence(rule,new Date(rule.start+"T00:00:00Z").getTime()-86400000);if(!first){setError("Tekrar günlerini ve bitişini kontrol edin.");return;}updated={...updated,recurrence:rule,occurrenceAt:first.at,dueDate:first.date,dueTime:rule.time,snoozedUntil:null,remindedFor:null,completed:false};}
    if(!editor.recurrence){updated={...updated,recurrence:null,...(previous?.recurrence||editor.dueDate!==previous?.dueDate||editor.dueTime!==previous?.dueTime?{occurrenceAt:null,snoozedUntil:null,remindedFor:null}:{})};}
    if (commit(current.some((task) => task.id === editor.id) ? current.map((task) => task.id === editor.id ? updated : task) : [updated, ...current])) { setEditor(null); setDraft(""); }
  }
  const remaining = tasks.filter((task) => !task.completed).length, shown = filterTasks(tasks, filter);
  return <section className={"section tasks-section " + (fullPage ? "tasks-page" : "")} aria-labelledby="tasks-heading">
    <div className="section-heading"><div>{!fullPage && <span className="eyebrow">GÜNÜN AKIŞI</span>}{fullPage ? <><h1 id="tasks-heading">Görevler</h1><p className="tasks-description">Yapılacaklarını planla, tamamladıklarını ayrı tut.</p></> : <h2 id="tasks-heading">Yapılacaklar</h2>}</div><span className="task-count">{remaining} KALDI</span></div>
    <div className="tasks-card surface"><form className="task-form" onSubmit={addTask}><label className="sr-only" htmlFor="new-task">Yeni görev</label><Icon name="plus" size={18} /><input id="new-task" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Yeni bir görev ekle..." maxLength={160} disabled={loaded.locked} /><button type="submit" disabled={!draft.trim() || loaded.locked} aria-label="Görev ekle"><Icon name="arrowRight" size={17} /></button></form>
      <button className="task-details-button" type="button" onClick={() => { setEditor(newTask(draft)); setDeleteId(null); }} disabled={loaded.locked}>Ayrıntılı ekle</button>
      <div className="task-filters" role="group" aria-label="Görev filtresi">{filters.map(([key, label]) => <button type="button" key={key} aria-pressed={filter === key} onClick={() => setFilter(key)}>{label}</button>)}</div>
      {error && <p className="tool-feedback error" role="alert">{error}</p>}
      {editor && <EditorDialog title={tasks.some(task => task.id === editor.id) ? "Görevi düzenle" : "Yeni görev"} description="Görev bilgilerini ve hatırlatmayı buradan düzenle." onClose={() => setEditor(null)} error={error}><form className="task-editor" onSubmit={saveEditor} onKeyDown={(event) => { if (event.key === "Escape") { event.preventDefault(); setEditor(null); } }} aria-label="Görev düzenleyici">
        <label className="archive-field">Görev<input autoFocus value={editor.text} onChange={(event) => setEditor({ ...editor, text: event.target.value })} maxLength={160} required /></label>
        <div className="archive-form-grid"><label className="archive-field">Tarih<input type="date" value={editor.dueDate ?? ""} onChange={(event) => setEditor({ ...editor, dueDate: event.target.value || null, reminder: event.target.value ? editor.reminder : false })} /></label><label className="archive-field">Saat<input type="time" value={editor.dueTime ?? ""} onChange={(event) => setEditor({ ...editor, dueTime: event.target.value || null, reminder: event.target.value ? editor.reminder : false })} /></label></div><RecurrenceFields key={editor.id} value={editor.recurrence??null} date={editor.dueDate??""} time={editor.dueTime??""} onChange={recurrence=>setEditor({...editor,recurrence})}/><div className="task-priority-field"><label className="archive-field">Öncelik<select value={editor.priority ?? "normal"} onChange={(event) => setEditor({ ...editor, priority: event.target.value === "important" ? "important" : "normal" })}><option value="normal">Normal</option><option value="important">Önemli</option></select></label></div><label className="reminder-toggle"><input type="checkbox" checked={editor.reminder ?? false} disabled={!editor.dueDate || !editor.dueTime} onChange={(event) => setEditor({ ...editor, reminder: event.target.checked })} />Hatırlatma</label>
        <p className="task-hint">Windows bildirimleri ACKDeck çalışırken gönderilir. Telefon eşitlemesi ve bildirimler açıksa, bulut hatırlatmaları bilgisayar kapalıyken de sürer.</p>
        <div className="settings-actions"><button className="button button-primary" type="submit">Kaydet</button><button className="button button-secondary" type="button" onClick={() => setEditor(null)}>Vazgeç</button></div>
      </form></EditorDialog>}
      <div className="task-list">{shown.length ? shown.map((task) => <div id={"task-" + task.id} className={`task-item ${task.completed ? "completed" : ""} ${!task.completed && task.dueDate && task.dueDate < localDateKey() ? "overdue" : ""} ${task.priority === "important" ? "important" : ""} ${initialId === task.id ? "record-highlight" : ""}`} key={task.id}>
        <button className="task-toggle" type="button" disabled={loaded.locked} onClick={() => commit(loadTasks().entries.map((item) => item.id === task.id ? completeOccurrence(item) : item))} aria-label={`${task.text}: ${task.completed ? "tamamlanmadı olarak işaretle" : "tamamlandı olarak işaretle"}`} aria-pressed={task.completed}>{task.completed && <Icon name="check" size={13} />}</button>
        <div className="task-text"><span>{task.text}</span><small className="task-meta">{task.priority === "important" && <strong>Önemli · </strong>}{task.dueDate ? task.dueDate.split("-").reverse().join(".") : "Tarihsiz"}{task.dueTime && " · " + task.dueTime}{!task.completed && task.dueDate && task.dueDate < localDateKey() && " · Tarihi geçti"}{task.recurrence && " · " + recurrenceLabel(task.recurrence)}{task.snoozedUntil && " · Ertelendi"}</small>{deleteId === task.id && <div className="task-delete-confirm"><span>Bu görev silinsin mi?</span><button type="button" onClick={() => { if (commit(loadTasks().entries.filter((item) => item.id !== task.id))) { offerUndo({ source: "tasks", record: task }); setDeleteId(null); } }}>Evet, sil</button><button type="button" onClick={() => setDeleteId(null)}>Vazgeç</button></div>}</div>
        <ActionMenu label={task.text+" işlemleri"}>{task.dueDate&&task.dueTime&&!task.completed&&<><button type="button" onClick={()=>snooze(task,15)}>15 dakika ertele</button><button type="button" onClick={()=>snooze(task,60)}>1 saat ertele</button><button type="button" onClick={()=>snooze(task,1440)}>Yarın hatırlat</button></>}<button className="task-details-button" type="button" disabled={loaded.locked} aria-label={task.text + " görevini düzenle"} onClick={() => { setEditor({ ...task }); setDeleteId(null); }}>Düzenle</button><button className="task-delete" type="button" disabled={loaded.locked} onClick={() => setDeleteId(task.id)} aria-label={`${task.text} görevini sil`}><Icon name="trash" size={16} /> Sil</button></ActionMenu>
      </div>) : <div className="empty-tasks">{tasks.length ? "Bu filtrede görev yok." : loaded.locked ? "Görevler okunamadı. Mevcut veriler korunuyor." : "Henüz görev yok. Yukarıdan bir görev ekleyebilirsin."}</div>}</div>
      <div className="task-footer"><span className="task-footer-dot" /> {tasks.length} görevden {tasks.length - remaining} tanesi tamamlandı</div>
    </div></section>;
}
