import { useEffect, useState } from "react";
import { loadTrash, restoreTrash, removeTrash, trashRecordExists, TRASH_RETENTION, type TrashSource } from "../trashStore";
const labels: Record<TrashSource, string> = { tasks: "Görev", notes: "Not", archive: "Arşiv", workspaces: "Çalışma alanı", shortcuts: "Kısayol", subscriptions: "Abonelik" };
export function TrashSettings() {
  const [loaded, setLoaded] = useState(loadTrash), [error, setError] = useState(""), [confirm, setConfirm] = useState<string | null>(null);
  useEffect(() => { const refresh = () => setLoaded(loadTrash()); window.addEventListener("ack-trash-changed", refresh); window.addEventListener("ack-data-changed", refresh); return () => { window.removeEventListener("ack-trash-changed", refresh); window.removeEventListener("ack-data-changed", refresh); }; }, []);
  const rows = loaded.entries.filter(t => t.deletedAt > Date.now() - TRASH_RETENTION && !trashRecordExists(t));
  return <section className="settings-card surface"><h2>Son silinenler</h2><p>Silinen kayıtları 30 gün boyunca geri getirebilirsin. Bu bilgisayarda tutulur; yedeklere ve telefon eşitlemesine dahil değildir. Bağlı gerçek dosyalar silinmez.</p>{loaded.locked && <p role="alert">Silinen kayıtlar okunamadı. Veriler korunuyor.</p>}{error && <p role="alert">{error}</p>}<div className="trash-list">{rows.map(t => <div className="trash-row" key={t.id}><div><strong>{"text" in t.record ? t.record.text : "title" in t.record ? t.record.title : t.record.name}</strong><small>{labels[t.source]} · {new Date(t.deletedAt).toLocaleDateString("tr-TR")} · {Math.max(1, Math.ceil((t.deletedAt + TRASH_RETENTION - Date.now()) / 86400000))} gün kaldı</small></div><button type="button" className="button button-secondary" onClick={() => { setError(restoreTrash(t.id) ? "" : "Kayıt geri getirilemedi. Mevcut veriler korunuyor."); }}>Geri getir</button>{confirm === t.id ? <div><span>Kalıcı silinsin mi?</span><button type="button" className="button button-secondary" onClick={() => { if (!removeTrash(t.id)) setError("Kayıt silinemedi."); setConfirm(null); }}>Evet, sil</button><button type="button" className="button button-secondary" onClick={() => setConfirm(null)}>Vazgeç</button></div> : <button type="button" className="button button-secondary" onClick={() => setConfirm(t.id)}>Kalıcı sil</button>}</div>)}</div>{!rows.length && !loaded.locked && <p>Son silinen kayıt yok.</p>}</section>;
}
