import { useEffect, useState } from "react";
import { weeklyPlan, weekDates } from "../../shared/weeklyPlan";
import { intelligenceData, weeklyReview } from "../productIntelligence";
import { taskDueAt } from "../taskStore";
import type { NavigationTarget } from "../navigation";
export function WeeklyPlan({ onNavigate, onAskAi }: {
    onNavigate: (target: NavigationTarget) => void;
    onAskAi: (text: string) => void;
}) {
    const [anchor, setAnchor] = useState(new Date()), [review, setReview] = useState(false), [, refresh] = useState(0);
    useEffect(() => { const update = () => refresh(v => v + 1); window.addEventListener("ack-data-changed", update); return () => window.removeEventListener("ack-data-changed", update); }, []);
    const data = intelligenceData(), days = weekDates(anchor), events = weeklyPlan(data.tasks.map(t => ({ ...t, dueAt: taskDueAt(t) })), data.subscriptions, anchor), summary = weeklyReview(data);
    return <section className="weekly-plan-page"><header className="feature-heading page-header"><div><h1>Haftalık plan</h1><p>Görevler, hatırlatmalar ve abonelik yenilemeleri.</p></div><button className="button button-secondary" onClick={() => setReview(v => !v)}>Haftayı toparla</button></header><div className="plan-toolbar"><button onClick={() => setAnchor(d => new Date(d.getFullYear(), d.getMonth(), d.getDate() - 7))}>← Önceki</button><button onClick={() => setAnchor(new Date())}>Bu hafta</button><button onClick={() => setAnchor(d => new Date(d.getFullYear(), d.getMonth(), d.getDate() + 7))}>Sonraki →</button></div>{data.warnings.map(w => <p key={w} role="alert">{w}</p>)}
 <div className="week-grid">{days.map(day => <section className="week-day" key={day}><button className="week-day-heading" onClick={() => onNavigate({ page: "tasks", intent: "new-task", date: day })}>{new Date(day + "T12:00:00").toLocaleDateString("tr-TR", { weekday: "short", day: "numeric", month: "short" })}<span>+</span></button>{events.filter(e => e.date === day).map((e, i) => <button className={`plan-event ${e.source} ${e.reminder ? "reminder" : ""}`} key={e.id + i} onClick={() => onNavigate({ page: e.source, id: e.id })}><small>{e.time ?? "Saat yok"} · {e.source === "subscriptions" ? "Abonelik" : "Görev"}</small><strong>{e.label}</strong></button>)}</section>)}</div>
 {review && <section className="weekly-review surface"><h2>Haftayı toparla</h2><div className="review-counts"><button onClick={() => onNavigate({ page: "tasks" })}>{summary.overdue.length} geciken görev</button><button onClick={() => onNavigate({ page: "inbox" })}>{summary.inbox?.length ?? "—"} işlenmemiş Gelen</button><button onClick={() => onNavigate({ page: "subscriptions" })}>{summary.subscriptions.length} yaklaşan abonelik</button><span>{summary.completed.length} kayıtlı tamamlanma</span></div>{summary.staleProjects.map(p => <button className="hub-record-row" key={p.id} onClick={() => onNavigate({ page: "projects", id: p.id })}>{p.name}<small>{p.nextStep || "14 gündür aktivite yok"}</small></button>)}<small>Geçmiş tutulmaya başlamadan önceki tamamlanmalar tahmin edilmez. {summary.unknownProjects.length > 0 && `${summary.unknownProjects.length} projenin kullanım geçmişi henüz yok.`}</small><button className="button button-primary" onClick={() => onAskAi("Haftamı toparla.")}>ACK AI ile toparla</button></section>}</section>;
}
