import { offerUndo } from "../recordUndo";
import { useEffect, useState } from "react";
import { loadWorkspaces, saveWorkspaces, pickTarget, saveUrl, type Workspace, type SavedTarget } from "../workHubStore";
import { loadProjectSnapshot } from "../projectStore";
import { launchWorkspace } from "../hubLaunch";
import { updateUsage, usageFor } from "../usageStore";
export function Workspaces({ initialId }: { initialId?: string }) {
  const [loaded, setLoaded] = useState(loadWorkspaces), [draft, setDraft] = useState<Workspace | null>(() => loadWorkspaces().entries.find(v => v.id === initialId) ?? null);
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), [deleting, setDeleting] = useState<string | null>(null), [url, setUrl] = useState("");
  const [projectId, setProjectId] = useState(""), [mode, setMode] = useState<"folder" | "vscode">("vscode");
  useEffect(() => { const refresh = () => setLoaded(loadWorkspaces()); window.addEventListener("ack-data-changed", refresh); return () => window.removeEventListener("ack-data-changed", refresh); }, []);
  const projects = loadProjectSnapshot().entries;
  function commit(entries: Workspace[]) { if (!saveWorkspaces(entries)) { setError("Çalışma alanı kaydedilemedi. Mevcut veriler korunuyor."); return false; } setLoaded(loadWorkspaces()); setError(""); return true; }
  async function addTarget(kind: SavedTarget["kind"]) { if (!draft || busy) return; setBusy(true); setError(""); try { const saved = kind === "url" ? await saveUrl(url) : await pickTarget(kind); if (saved) { setDraft({ ...draft, items: [...draft.items, { id: crypto.randomUUID(), name: saved.name.slice(0, 160), type: "target", saved }] }); setUrl(""); } } catch { setError(kind === "url" ? "Geçerli bir http veya https adresi girin." : "Öğe seçilemedi. Seçilen uygulama komut veya betik çalıştırıcısı olmamalı."); } finally { setBusy(false); } }
  async function start(id: string) { if (busy) return; setBusy(true); setError(""); try { const result = await launchWorkspace(id); setError(result.errors.join(" ") || (result.opened ? "Çalışma alanı açıldı." : "Çalışma alanına önce bir öğe ekleyin.")); setLoaded(loadWorkspaces()); } catch { setError("Çalışma alanı açılamadı. Kayıtları kontrol edin."); } finally { setBusy(false); } }
  return <section className="hub-page"><div className="section-heading"><div><h1>Çalışma Alanları</h1><p>Kayıtlı projeleri, dosyaları ve uygulamaları tek seferde birlikte aç.</p></div><button className="button button-primary" type="button" disabled={busy || loaded.locked} onClick={() => setDraft({ id: crypto.randomUUID(), name: "", description: "", icon: "", createdAt: Date.now(), lastUsedAt: 0, useCount: 0, pinned: false, items: [] })}>+ Çalışma Alanı</button></div>
    {(error || loaded.error) && <p role="status" className="tool-feedback">{error || loaded.error}</p>}
    {draft && <form className="surface hub-editor" onKeyDown={e => { if (e.key === "Escape" && !busy) setDraft(null); }} onSubmit={e => { e.preventDefault(); const current = loadWorkspaces(); if (commit([...current.entries.filter(v => v.id !== draft.id), draft])) setDraft(null); }}>
      <h2>Çalışma alanını düzenle</h2><label>Ad<input required maxLength={160} autoFocus value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>Kısa açıklama<input maxLength={2000} value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><details className="advanced-fields"><summary>Simge</summary><label>Simge / emoji (isteğe bağlı)<input maxLength={16} value={draft.icon} onChange={e => setDraft({ ...draft, icon: e.target.value })} /></label></details>
      <h3>Açılacaklar</h3>{draft.items.map(item => <div className="hub-item" key={item.id}><span title={item.type === "target" ? item.saved.target : "Kayıtlı proje"}>{item.name}</span><button type="button" disabled={busy} onClick={() => setDraft({ ...draft, items: draft.items.filter(v => v.id !== item.id) })}>Öğeyi Kaldır</button></div>)}
      {draft.items.length < 30 && <><div className="hub-actions"><label>Mevcut proje<select value={projectId} onChange={e => setProjectId(e.target.value)}><option value="">Proje seç</option>{projects.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Açma şekli<select value={mode} onChange={e => setMode(e.target.value as typeof mode)}><option value="vscode">VS Code</option><option value="folder">Explorer</option></select></label><button type="button" disabled={busy || !projectId} onClick={() => { const project = projects.find(v => v.id === projectId); if (project) setDraft({ ...draft, items: [...draft.items, { id: crypto.randomUUID(), name: project.name, type: "project", projectId, mode }] }); }}>Projeyi Ekle</button></div>
      <div className="hub-actions">{([['file', 'Dosya Ekle'], ['folder', 'Klasör Ekle'], ['application', 'Uygulama Ekle']] as const).map(([kind, label]) => <button key={kind} type="button" disabled={busy} onClick={() => void addTarget(kind)}>{label}</button>)}</div><label>Web adresi<input type="url" maxLength={4096} placeholder="https://..." value={url} onChange={e => setUrl(e.target.value)} /></label><button type="button" disabled={busy || !url} onClick={() => void addTarget("url")}>Web Adresi Ekle</button></>}
      <small>Uygulamalar yalnızca seçtiğin .exe dosyalarıdır. Komut veya argüman çalıştırılmaz.</small><div className="hub-actions"><button type="submit" className="button button-primary" disabled={busy || !draft.name.trim()}>Kaydet</button><button type="button" disabled={busy} onClick={() => setDraft(null)}>İptal</button></div>
    </form>}
    {!loaded.entries.length && !draft && <p className="dashboard-empty">Henüz çalışma alanı yok. İlk çalışma alanını oluştur.</p>}
    <div className="hub-grid">{loaded.entries.map(item => <article key={item.id} className="surface hub-card"><h2>{item.icon} {item.name}</h2><p>{item.description || "Açıklama eklenmedi."}</p><small>{item.items.length} öğe · {item.useCount} kez kullanıldı</small><div className="hub-actions"><button className="button button-primary" type="button" disabled={busy} onClick={() => void start(item.id)}>Çalışmaya Başla</button><details className="overflow-menu"><summary aria-label={item.name+" işlemleri"}>⋯</summary><div><button type="button" disabled={busy} onClick={() => { const pinned = !usageFor("workspaces", item.id).pinned; if (updateUsage("workspaces", item.id, pinned)) commit(loadWorkspaces().entries.map(v => v.id === item.id ? { ...v, pinned } : v)); else setError("Sabitleme kaydedilemedi."); }}>{usageFor("workspaces", item.id).pinned ? "Sabitlemeyi Kaldır" : "Sabitle"}</button><button type="button" disabled={busy} onClick={() => setDraft(item)}>Düzenle</button><button type="button" disabled={busy} onClick={() => setDeleting(item.id)} className="danger-action">Kaydı Sil</button></div></details></div></article>)}</div>
    {deleting && <div className="surface hub-editor" role="alertdialog" aria-label="Çalışma alanını sil"><p>Yalnızca ACKDeck çalışma alanı kaydı silinecek. Bağlı dosyalar, uygulamalar ve projeler korunur.</p><button type="button" disabled={busy} onClick={() => { const removed = loadWorkspaces().entries.find(v => v.id === deleting); if (commit(loadWorkspaces().entries.filter(v => v.id !== deleting))) { if (removed) offerUndo({ source: "workspaces", record: removed }); setDeleting(null); if (draft?.id === deleting) setDraft(null); } }}>Kaydı Sil</button><button type="button" onClick={() => setDeleting(null)}>İptal</button></div>}
  </section>;
}
