import { useState } from "react";
import type { Recurrence } from "./recurrence";
const days=[[1,"Pzt"],[2,"Sal"],[3,"Çar"],[4,"Per"],[5,"Cum"],[6,"Cmt"],[0,"Paz"]] as const;
export function RecurrenceFields({value,date,time,onChange}:{value:Recurrence|null;date:string;time:string;onChange:(rule:Recurrence|null)=>void}) {
  const guess=!value?"none":value.frequency==="daily"&&value.interval===1?"daily":value.frequency==="monthly"&&value.interval===1?"monthly":value.frequency==="weekly"&&value.interval===1?(value.weekdays.join()==="1,2,3,4,5"?"weekdays":value.weekdays.length===1?"weekly":"days"):"custom";
  const [mode,setMode]=useState(guess);
  function choose(key:string){setMode(key);if(key==="none"){onChange(null);return;}const start=date||new Date().toLocaleDateString("en-CA"),day=new Date(start+"T12:00:00").getDay();onChange({frequency:key==="monthly"?"monthly":["weekly","days","weekdays"].includes(key)?"weekly":"daily",interval:1,weekdays:key==="weekdays"?[1,2,3,4,5]:[day],dayOfMonth:Number(start.slice(8)),start,time:time||"09:00",timezone:value?.timezone??Intl.DateTimeFormat().resolvedOptions().timeZone,endDate:null,count:null});}
  return <div className="recurrence-fields"><label className="archive-field">Tekrar<select value={mode} onChange={e=>choose(e.target.value)}><option value="none">Tek sefer</option><option value="daily">Her gün</option><option value="weekdays">Hafta içi</option><option value="weekly">Her hafta</option><option value="days">Belirli günler</option><option value="monthly">Her ay</option><option value="custom">Özel</option></select></label>
    {value&&<>{mode==="custom"&&<div className="recurrence-custom"><label className="archive-field">Aralık<input type="number" min={1} max={365} value={value.interval} onChange={e=>onChange({...value,interval:Number(e.target.value)})}/></label><label className="archive-field">Dönem<select value={value.frequency} onChange={e=>onChange({...value,frequency:e.target.value as Recurrence["frequency"]})}><option value="daily">Gün</option><option value="weekly">Hafta</option><option value="monthly">Ay</option></select></label></div>}
    {value.frequency==="weekly"&&mode!=="weekdays"&&<div className="weekday-options" role="group" aria-label="Tekrar günleri">{days.map(([day,label])=><button key={day} type="button" aria-pressed={value.weekdays.includes(day)} onClick={()=>onChange({...value,weekdays:value.weekdays.includes(day)?value.weekdays.filter(d=>d!==day):[...value.weekdays,day].sort()})}>{label}</button>)}</div>}
    {value.frequency==="monthly"&&<label className="archive-field">Ayın günü<input type="number" min={1} max={31} value={value.dayOfMonth} onChange={e=>onChange({...value,dayOfMonth:Number(e.target.value)})}/><small>Kısa aylarda ayın son günü kullanılır.</small></label>}
    <div className="recurrence-ending"><h4>Tekrarın süresi</h4><label className="archive-field">Bitiş<select value={value.endDate?"date":value.count!==null?"count":"never"} onChange={e=>onChange({...value,endDate:e.target.value==="date"?date||value.start:null,count:e.target.value==="count"?10:null})}><option value="never">Sürekli devam et</option><option value="date">Şu tarihte</option><option value="count">Belirli sayıda tekrar</option></select></label>{value.endDate!==null&&<label className="archive-field">Son tarih<input type="date" min={value.start} value={value.endDate} onChange={e=>onChange({...value,endDate:e.target.value})}/></label>}{value.count!==null&&<label className="archive-field">Tekrar sayısı<input type="number" min={1} max={100000} value={value.count} onChange={e=>onChange({...value,count:Number(e.target.value)})}/></label>}<small>Saat dilimi: {value.timezone}. Kaçırılan tekrarlar birikmez.</small></div></>}
  </div>;
}
