import { useState, type FormEvent } from "react";
import { validSubscription, type Subscription } from "./subscriptions";
export function newSubscription():Subscription {const now=Date.now();return {id:crypto.randomUUID(),name:"",category:"Diğer",amount:0,currency:"TRY",cycle:"monthly",periodDays:30,nextPayment:new Date().toLocaleDateString("en-CA"),autoRenew:true,status:"active",website:"",note:"",icon:"",reminderDays:null,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,createdAt:now,updatedAt:now};}
export function SubscriptionForm({initial,onSave,onCancel,busy=false,showHeading=true}:{initial:Subscription;onSave:(s:Subscription)=>Promise<void>|void;onCancel:()=>void;busy?:boolean;showHeading?:boolean}) {
  const [draft,setDraft]=useState(initial),[error,setError]=useState("");
  function update<K extends keyof Subscription>(key:K,value:Subscription[K]){setDraft(s=>({...s,[key]:value}));}
  async function submit(e:FormEvent){e.preventDefault();const next={...draft,name:draft.name.trim(),updatedAt:Date.now()};if(!validSubscription(next)){setError("Ad, tutar, tarih ve dönem bilgilerini kontrol edin.");return;}try{await onSave(next);}catch{setError("Abonelik kaydedilemedi. Mevcut kayıtlar korunuyor.");}}
  return <form className="subscription-form hub-editor surface" onSubmit={e=>void submit(e)} onKeyDown={e=>{if(e.key==="Escape")onCancel();}}>{showHeading && <div className="subscription-form-heading"><h2>{initial.name?"Aboneliği düzenle":"Abonelik ekle"}</h2><button type="button" aria-label="Abonelik düzenleyicisini kapat" disabled={busy} onClick={onCancel}>×</button></div>}
    <label className="archive-field">Ad<input autoFocus required maxLength={160} value={draft.name} onChange={e=>update("name",e.target.value)} placeholder="Örn. YouTube Premium"/></label>
    <div className="archive-form-grid"><label className="archive-field">Tutar<input required type="number" min={0} max={1e9} step="0.01" value={draft.amount} onChange={e=>update("amount",Number(e.target.value))}/></label><label className="archive-field">Para birimi<select value={draft.currency} onChange={e=>update("currency",e.target.value as Subscription["currency"])}>{["TRY","USD","EUR","GBP"].map(c=><option key={c}>{c}</option>)}</select></label></div>
    <div className="archive-form-grid"><label className="archive-field">Ödeme dönemi<select value={draft.cycle} onChange={e=>update("cycle",e.target.value as Subscription["cycle"])}><option value="monthly">Aylık</option><option value="yearly">Yıllık</option><option value="weekly">Haftalık</option><option value="custom">Özel dönem</option></select></label><label className="archive-field">Sonraki ödeme<input type="date" required value={draft.nextPayment} onChange={e=>update("nextPayment",e.target.value)}/></label></div>
    {draft.cycle==="custom"&&<label className="archive-field">Kaç günde bir?<input type="number" min={1} max={3650} required value={draft.periodDays} onChange={e=>update("periodDays",Number(e.target.value))}/></label>}
    <label className="archive-field">Ödeme hatırlatması<select value={draft.reminderDays===null?"off":[0,1,3,7].includes(draft.reminderDays)?String(draft.reminderDays):"custom"} onChange={e=>update("reminderDays",e.target.value==="off"?null:e.target.value==="custom"?2:Number(e.target.value))}><option value="off">Kapalı</option><option value="0">Aynı gün</option><option value="1">1 gün önce</option><option value="3">3 gün önce</option><option value="7">7 gün önce</option><option value="custom">Özel</option></select></label>
    {draft.reminderDays!==null&&![0,1,3,7].includes(draft.reminderDays)&&<label className="archive-field">Kaç gün önce?<input type="number" min={0} max={365} value={draft.reminderDays} onChange={e=>update("reminderDays",Number(e.target.value))}/></label>}
    <div className="subscription-options">
      <div className="archive-form-grid"><label className="archive-field">Kategori<input maxLength={80} value={draft.category} onChange={e=>update("category",e.target.value)} placeholder="Örn. Eğlence, İş"/></label><label className="archive-field">Durum<select value={draft.status} onChange={e=>update("status",e.target.value as Subscription["status"])}><option value="active">Aktif</option><option value="paused">Duraklatıldı</option><option value="cancelled">İptal edildi</option></select></label></div>
      <label className="reminder-toggle"><input type="checkbox" checked={draft.autoRenew} onChange={e=>update("autoRenew",e.target.checked)}/>Otomatik yenileme</label>
      <label className="archive-field">Not <span className="field-optional">İsteğe bağlı</span><textarea rows={2} maxLength={2000} value={draft.note} onChange={e=>update("note",e.target.value)} placeholder="Bu abonelikle ilgili kısa bir not"/></label>
    </div>
    <small>Hatırlatma saat 09:00'da hazırlanır. Kart veya ödeme bilgisi eklemeyin.</small>{error&&<p className="error" role="alert">{error}</p>}<div className="settings-actions"><button className="button button-primary" disabled={busy}>Kaydet</button><button type="button" className="button button-secondary" disabled={busy} onClick={onCancel}>Vazgeç</button></div>
  </form>;
}
