CREATE TABLE devices (id TEXT PRIMARY KEY, name TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, revoked_at INTEGER, last_seen INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE pairing_codes (hash TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, used_at INTEGER);
CREATE INDEX pairing_expiry ON pairing_codes(expires_at);
CREATE TABLE push_subscriptions (device_id TEXT PRIMARY KEY REFERENCES devices(id), subscription TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, updated_at INTEGER NOT NULL);
CREATE TABLE records (kind TEXT NOT NULL CHECK(kind IN ('tasks','notes')), id TEXT NOT NULL, version INTEGER NOT NULL, data TEXT, deleted INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL, PRIMARY KEY(kind,id));
CREATE TABLE mutations (id TEXT PRIMARY KEY, actor TEXT NOT NULL, request_hash TEXT NOT NULL, response TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX mutation_age ON mutations(created_at);
CREATE TABLE changes (seq INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL, record_id TEXT NOT NULL, version INTEGER NOT NULL);
CREATE INDEX changes_record ON changes(kind,record_id);
CREATE TABLE inbox_items (id TEXT PRIMARY KEY, kind TEXT NOT NULL, title TEXT NOT NULL, content TEXT NOT NULL DEFAULT '', mime TEXT, size INTEGER, kv_key TEXT, expires_at INTEGER, handled INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, device_id TEXT NOT NULL REFERENCES devices(id));
CREATE INDEX inbox_recent ON inbox_items(created_at DESC);
CREATE TABLE workspace_mirrors (id TEXT PRIMARY KEY, name TEXT NOT NULL, icon TEXT NOT NULL, description TEXT NOT NULL);
CREATE TABLE remote_commands (id TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK(kind='launch_workspace'), workspace_id TEXT NOT NULL, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, state TEXT NOT NULL DEFAULT 'pending', queued_offline INTEGER NOT NULL, result TEXT, device_id TEXT NOT NULL REFERENCES devices(id));
CREATE INDEX remote_pending ON remote_commands(state,expires_at);
CREATE TABLE desktop_state (id INTEGER PRIMARY KEY CHECK(id=1), last_seen INTEGER NOT NULL DEFAULT 0);
INSERT INTO desktop_state(id,last_seen) VALUES(1,0);
CREATE TABLE reminders (task_id TEXT PRIMARY KEY, generation TEXT NOT NULL, due_at INTEGER NOT NULL, timezone TEXT NOT NULL, active INTEGER NOT NULL);
CREATE INDEX reminders_due ON reminders(active,due_at);
CREATE TABLE reminder_deliveries (generation TEXT NOT NULL, device_id TEXT NOT NULL, state TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, retry_at INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(generation,device_id));
CREATE INDEX delivery_retry ON reminder_deliveries(state,retry_at);
CREATE TABLE rate_limits (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, reset_at INTEGER NOT NULL);
CREATE INDEX rate_expiry ON rate_limits(reset_at);
